### ISSUE TITLE
Password-protected connections file bad behavior.

### ISSUE THREAD

**Issue by artyomk3d** [mRemoteNG/mRemoteNG#1022]
## Current Behavior

Password-protected connections file getting overwritten blank if password not entered on startup.

## Possible Solution

mRemoteNg should create blank connections file with new name if password  does not provided for current connections file.

## Steps to Reproduce (for bugs)

1. Connections file is password-protected.
2. Option "Save connections on exit " is checked.
3. You start mRemoteNg - program asks password for the file. You press "cancel" - program opens with blank file. 
4. You exit mRemoteNg.
5. Your original connections file is overwritten with blank file. You need to restore it from backup.
6. This happens both with default or custom connections file name.

## Your Environment

* Version used: 1.76.4.16261
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by sparerd** [comment]
Related to #961

**Comment by sparerd** [comment]
I've committed a fix for this in 9659ac1. We will now prompt for what to do when decryption fails, similar to how we prompt when a connection file cant be found. This should no longer cause the confCons file to be overwritten.

This will be available in the next v1.76 release. Note that the change log will reference #961 since that is essentially the same issue and was entered first.
