### ISSUE TITLE
Original connection settings modified on duplicate connection

### ISSUE THREAD

**Issue by womby** [mRemoteNG/mRemoteNG#1076]
Hey,

I've noticed this one for a while, but I thought I was just being incompetent! However, this morning I was able to track this down:

1. In options, enable "Set hostname like display name when creating or renaming connections"
2. Create a folder with most RDP settings defined, and enable all inheritance options (Bar Display Name & Connection Hostname/IP)
3. Create a connection inside this folder, only changing the Display Name (which then changes the Connection Hostname/IP automatically as per Option set in step 1.)
4. Duplicate this connection, and rename this dupe with the F2 key. Click on it, to change the focus of the properties window to it.
5. Go to the inheritance settings of this new connection, and disable inheritance on the 'Username' 'Password' & 'Domain' fields.
5. Go back to the properties of this new connection, and notice that you're now back to the original connection. Unless you notice this then and there, you'll begin to change the settings of the original connection 👎 

Windows Version: 10.0.17134 Build 17134
mRemoteNG Version: 1.75.7012.16814

**Comment by sparerd** [comment]
Im able to replicate this in v1.76.6 as well

**Comment by sparerd** [comment]
This is happening due to a bug in the duplication process. ConnectionInfos have a reference to their inheritance objects and their inheritance objects also have a reference back to their parent connectioninfo.

In this case, the duplication isn't setting the new inheritance object correctly. The chain should be:
`con1 -> inheritance1 -> con1` so we can effectively reference back and forth.

But when duplicating, the chain becomes: `con2 -> inheritance2 -> con1`. This breaks the chain and produces the odd effect you're seeing, where you click on `con2` to change its inheritance, but then when you click the 'view properties' button you are now looking at `con1`.

It's important to note that this bug doesn't survive between app restarts. Saving and then restarting the app will make things work as you expect. That being said, it's still probably pretty annoying. I'm working on a fix now.

**Comment by sparerd** [comment]
Thanks for reporting the bug! This has been fixed and will be in v1.76.7.

**Comment by womby** [comment]
@sparerd Thanks David, that's great!
