### ISSUE TITLE
COM object that has been separated from its underlying RCW cannot be used

### ISSUE THREAD

**Issue by richard-scott** [mRemoteNG/mRemoteNG#1146]
## Expected Behavior
Dragging application from Monitor 1 to Monitor 2 should work.

## Current Behavior
Application causes an error and the quits.
[bug.txt](https://github.com/mRemoteNG/mRemoteNG/files/2491633/bug.txt)

## Steps to Reproduce (for bugs)

1. Open an RDP session.
2. Close RDP session
3. Drag App from one monitor to the other.

## Context
It hampers my need to move the application from one window to the next.

## Your Environment

* Version used:
mRemoteNG        : 1.76.10.42392
* Operating System and version (e.g. Windows 10 1709 x64):
Caption                 : Microsoft Windows 10 Pro
Version                 : 10.0.17134
ServicePackMajorVersion : 0
OSArchitecture          : 64-bit

**Comment by sparerd** [comment]
Sorry that is happening @richard-scott. Few questions for you so we can narrow things down:
- Does this happen every time you take the steps you outlined above, or is it intermittent?
- Does this happen with any other RDP clients (mstsc, RDCMan, etc)?

The stack trace indicates the issue is in the RDP library when it tries to call from a .NET managed wrapper to an system COM object. It is likely a bug with that specific build of Win10.

The only change in mRemoteNG that might have caused this to manifest now is we switched from compiling for .NET 4.0 to .NET 4.6. That change along with your Win10 build could be the reason for failure.

I haven't been able to replicate the bug on a Win10 14393 build. I think I have a machine with 1709 or 1803. I can retest on that when I'm home.

**Comment by richard-scott** [comment]
I can't seem to reproduce this following some automatic Windows updates.
