### ISSUE TITLE
Ignore prerequisites not working on new version

### ISSUE THREAD

**Issue by nicolasvahidzein** [mRemoteNG/mRemoteNG#1178]
We cannot install without prerequisites on the new install. It shows a window in the installer with the options listed but does not execute the installer itself.

**Comment by nicolasvahidzein** [comment]
this is the version: Stable v1.76.11

**Comment by kmscode** [comment]
@sparerd With the prereq fixes having been replaced multiple times over - maybe we should see about just doing a version check on the MSTSC client library rather than looking for the fix?


@nicolasvahidzein Could you provide some more details? Screenshots?

Check %TEMP% for an MSI log. For example:
C:\Users\[user name]\AppData\Local\Temp\MSI[random chars].LOG

**Comment by nicolasvahidzein** [comment]
@kmscode Hey buddy, it now works with the beta version of the app.

**Comment by sparerd** [comment]
@kmscode Yea, that would probably be easier overall.

I also started working on some RDP changes that would allow users to select the rdp version they wanted to use for a connection and allow show what is available on the machine at runtime. This would allow us to completely remove the prereq checks from the installer.
