### ISSUE TITLE
[Feature Request] Port Knocking

### ISSUE THREAD

**Issue by tenvpole** [mRemoteNG/mRemoteNG#1212]
## Expected Behavior
There is no port knocking

## Current Behavior
Feature is missing

## Possible Solution
Realize sending tcp/udp packets to selected ports, or add PS scripts support :)

## Context
This is a feature I use on a daily basis.

## Your Environment

* Version used: 1.76.11.40527
* Operating System: Windows 10 1709 x64

**Comment by sparerd** [comment]
You can run PS scripts against connections using the External Tools feature

**Comment by mjmooney** [comment]
Future enhancement maybe?

While definitely possible via scripting, it could still be very useful to build-in and provide a simpler, more streamlined method to set up for those that either don't know how, or like me that tend _not_ to configure unless absolutely needed, simply because it's a hassle with low ROI, but when I use Terminus on my Android phone, I'll set this up across the board when needed because it's baked in.

Cheers,
M

**Comment by farosch** [comment]
Just like you said:

> it's a hassle with low ROI

We cannot implement every so little feature just because it might be useful to 1% of our customer base. The external tools system exists exactly because of this, so that people with very specific needs can implement verious things via scripting, other applications and so forth.
Implementing and maintaining features like this takes precious programming time from issues that would really benefit the whole community. And let's be honest: We do have a shitload of these...
