### ISSUE TITLE
VNC connection is notworking with mac os mojave 10.14.2.

### ISSUE THREAD

**Issue by sumankumarpagadala** [mRemoteNG/mRemoteNG#1215]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by farosch** [comment]
You made [the same issue over at tigervnc](https://github.com/TigerVNC/tigervnc/issues/780) which kinda makes me think the real problem here is your macOS Mojave.
Nevertheless you need to provide at least some information. If you want people to solve a problem for you at least take the time to describe your problem properly. "Not working" is nothing anyone can work with.

**Comment by habiwan** [comment]
## Expected Behavior
mRemoteng should open MacOS Mojave via VNC
## Current Behavior
Wehn opening a VNC connection to a Macos Mojave Machine, the connection opens briefly and closes again
## Possible Solution
Other VNC capable software give the error "encryption not supported"
It seems the solution has to be for apple to tell you guys how to connect now, no?
## Steps to Reproduce (for bugs)
connect to a MacOS Mojave system with mRemoteng using VNC
## Context
This connections have been working in previous versions of MacOS, I suspect Apple has added further security to VNC connections or encryptions that are not opensourced or they use now since Mojave a propietary VNC connection as connecting 2 macs via Screeshare works, however it does juts close on Windows -> mRemoteng -> VNC to Mojave (via IP Address)
## Your Environment
* Version used: 1.76.11 (2018-10-18) (also tested with RealVNC, and UltraVNC)
* Operating System and version (e.g. Windows 10 1709 x64):  10.0.17134.254 x64 (tested with all Win10)

**Comment by farosch** [comment]
![image](https://user-images.githubusercontent.com/22905106/66087100-8d3d0980-e576-11e9-8d38-8749e665b91f.png)

Taken from here: https://apple.stackexchange.com/questions/342161/macos-mojave-remote-access-login-screen-stuck-on-infinite-loading-spinner

@sumankumarpagadala Can you please confirm if this is fixing your issue or if you don't have this issue at all anymore?
