### ISSUE TITLE
Connection panel not translated when added

### ISSUE THREAD

**Issue by farosch** [mRemoteNG/mRemoteNG#1238]
The connection panel is not translated when added to the form until activated:
![2018-12-25_23-17-37](https://user-images.githubusercontent.com/22905106/50426986-b28c4100-089b-11e9-8808-537e7af0e2c4.gif)

**Comment by sparerd** [comment]
This seems to be due to the `ApplyLanguage()` call being in the form's OnLoad event handler. The form's `TabName` property is set to the default "Connections" value until the form is loaded, then it changes to the correct "Verbindungen" value for Deutsch. Moving `ApplyLanguage()` to the very end of the form's constructor fixes the issue. I'll submit the fix for this shortly.
