### ISSUE TITLE
Export does not support Putty sessions

### ISSUE THREAD

**Issue by imtrobin** [mRemoteNG/mRemoteNG#1272]
Hi, I have setup connections with Putty Saved sessions that has SSH key Auth. After I export, and import it back on another machine, the Putty Saved Sessions are not imported back..

win10

**Comment by farosch** [comment]
Yes, this is by design:
The PuTTY sessions showing in mrng are nothing more but a reflection of your saved sessions in PuTTY.
Importing a config file into mRemoteNG does not alternate your PuTTY settings and neither should it.
These are two seperate applications and they will be treated this way, especially as PuTTY will at some time be completely removed from mRemoteNG (#181) this is something we won't implement.
