### ISSUE TITLE
Option to hide navigation buttons on tab bar

### ISSUE THREAD

**Issue by mblissmer** [mRemoteNG/mRemoteNG#1328]
It would be great to have an option to hide the arrows and close button on the right side of the tab bar. When you're in an RDP session and juggling a bunch of windows, there are already multiple X's up in that corner, and more than once I've tried to close a window in my RDP session and nearly closed the RDP session itself. On by default is ideal, but an option to remove them would be great!

**Comment by farosch** [comment]
Hi @mblissmer
Since the last release of mrng a lot of things have changed. We have replaced the magiclib library with dockpanelsuite. As of the current develop branch the tabs look like this:
![image](https://user-images.githubusercontent.com/22905106/54083280-bd466600-4321-11e9-81d4-0ff75d52a34c.png)
So there are no closing/arrow buttons on the far right side of the tabs anymore.
Feel free to reopen this issue if you have any further questions/suggestions.
