### ISSUE TITLE
Crashes after opening (started after latest update to 1.76.18 (2019-03-20):  )

### ISSUE THREAD

**Issue by prasanna-sk** [mRemoteNG/mRemoteNG#1366]
## Current Behavior
Application crashes immediately with below error.

`SSH, Telnet and Rlogin client has stopped working`

![image](https://user-images.githubusercontent.com/13476189/54706815-086c3000-4afd-11e9-97f9-f4feb186045f.png)

## Steps to Reproduce (for bugs)
1. In Windows 7, after the latest update 1.76.18 (2019-03-20), open the application
2. Connect to any connection (I use ssh)
3. A window with the error described above will pop-up

## Context
Daily usage. Trying to connect to unix servers.
Not able to connect to any unix servers.

## Your Environment
* Version used: 1.76.18 (2019-03-20):
* Operating System and version : Windows 7 SP1

**Comment by prasanna-sk** [comment]
[mRemoteNG.log](https://github.com/mRemoteNG/mRemoteNG/files/2989480/mRemoteNG.log)

[PuTTYNG.exe.3148.dmp.txt](https://github.com/mRemoteNG/mRemoteNG/files/2989482/PuTTYNG.exe.3148.dmp.txt)

.dmp file has been renamed to .dmp.txt

**Comment by kmscode** [comment]
I'll most likely need to rebuild putty with symbols and have you reproduce the crash with that version and send a new dump file. Stay tuned...

**Comment by kmscode** [comment]
https://ci.appveyor.com/project/mremoteng/puttyng-77pmq/build/artifacts

Try getting the puttyng.exe from here and see if you can reproduce the crash. If so, attach a new dump and I'll attach it to the debugger with the matched symbols.

Thanks!

**Comment by prasanna-sk** [comment]
I got the exe and the pdb files from the link and copy/replaced to installation dir (C:\Program Files (x86)\mRemoteNG). Was able to reproduce crash with the same steps as before. 
 
Let me know if you need anything else. Thanks.

Here are the files.
[PuTTYNG.exe.17280.dmp.txt](https://github.com/mRemoteNG/mRemoteNG/files/2990300/PuTTYNG.exe.17280.dmp.txt)
[mRemoteNG.log](https://github.com/mRemoteNG/mRemoteNG/files/2990301/mRemoteNG.log)

**Comment by kmscode** [comment]
The crash doesn't appear to be related to any of the puttyng specific customization that we make. And I'm 99.999% sure that I didn't mess up the merge or build....

There were A LOT of changes in putty between 0.70 and 0.71 - so I'm guessing that this problem didn't occur with mremoteng/puttyng 1.76.16/0.70.0.1 and below? As a workaround, you could replace the puttyng 0.71 binary with the previous build:
https://ci.appveyor.com/project/mremoteng/puttyng-77pmq/builds/21895179/artifacts

Looks like you have some 3rd party GSSAPI libraries on your system that are getting loaded into the putty process: C:\Program Files\MIT\Kerberos\bin\gssapi32.dll

Looks like this is [Kerberos for Windows 4.1](https://web.mit.edu/kerberos/kfw-4.1/kfw-4.1.html) based on the binary times.

Best I can tell, the putty process is failing within that gssapi32.dll:
![image](https://user-images.githubusercontent.com/16654335/54730704-b65cf600-4b60-11e9-98d0-91bfb8fafb6c.png)

I would suggest [pulling down putty 0.71 directly](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html) and testing with that outside of mremoteng. I suspect that you'll have the same crash with that build. In which case, you shoud reach out to the [MIT Kerberos d-lists](http://web.mit.edu/Kerberos/mail-lists.html) and report the problem/bug there... You may also want to submit a bug directly to putty since they might be able to assist as well:
https://www.chiark.greenend.org.uk/~sgtatham/putty/feedback.html#feedback-bugs



The only other comment that I have is your VC runtime couldn't be identified for loading symbols. Make sure you have the latest and are all patched up accordingly. The binary dates are from Jan 2018 - the [latest 2015 runtime](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) was released in Jul 2016 - but I'm sure it was patched numerous times since then. (I'm on Win 10 and my 2015 runtime dates are from Nov 2018).

![image](https://user-images.githubusercontent.com/16654335/54730979-1607d100-4b62-11e9-85cd-90465e9516ae.png)



Hope that helps...

**Comment by aldago** [comment]
It looks like this is fixed in the latest putty snapshot:

Fixed in current snapshots

    Bugs (and semi-bugs)
        gssapi-kfw-crash: GSSAPI with MIT Kerberos-for-Windows or third-party DLL crashes 

 Attempting to use GSSAPI authentication with MIT Kerberos-for-Windows, or a third-party GSSAPI Windows DLL, would cause PuTTY to crash early in an SSH connection.

Since GSSAPI authentication and key exchange are enabled by default, the mere presence of MIT Kerberos is usually sufficient to cause affected versions of PuTTY to crash.

This bug can be worked around by disabling both of the "Attempt GSSAPI" options on the Connection / SSH / Auth / GSSAPI tab in the PuTTY configuration. 

I tested the solution of disabling Attemp GSSAPI and it works fine.

**Comment by prasanna-sk** [comment]
> It looks like this is fixed in the latest putty snapshot:
> 
> Fixed in current snapshots
> 
> ```
> Bugs (and semi-bugs)
>     gssapi-kfw-crash: GSSAPI with MIT Kerberos-for-Windows or third-party DLL crashes 
> ```
> Attempting to use GSSAPI authentication with MIT Kerberos-for-Windows, or a third-party GSSAPI Windows DLL, would cause PuTTY to crash early in an SSH connection.
> 
> Since GSSAPI authentication and key exchange are enabled by default, the mere presence of MIT Kerberos is usually sufficient to cause affected versions of PuTTY to crash.
> 
> This bug can be worked around by disabling both of the "Attempt GSSAPI" options on the Connection / SSH / Auth / GSSAPI tab in the PuTTY configuration.
> 
> I tested the solution of disabling Attemp GSSAPI and it works fine.

The workaround suggested worked for me. Closing for now. Thanks.
