### ISSUE TITLE
REGRESSION: Smart Cards redirection to Remote Desktop not working

### ISSUE THREAD

**Issue by bluikko** [mRemoteNG/mRemoteNG#1465]
In 1.77.0.41252 the logon to Microsoft Windows servers with Smart Card does not work anymore.

It used to work a few versions ago.

## Expected Behavior
If "Smart Cards" is set to "Yes" (either directly or inherited), then opening a Remote Desktop session to a Windows Server should allow Smart Card logon.

## Current Behavior
Logon with Smart Card is impossible, user is presented with a logon screen.

Running "mstsc.exe" outside of mRemoteNG and Smart Card logon works to the exact same servers, as expected, when Smart Card redirection is enabled. The only difference that I can see is that running "mstsc.exe" manually works, whereas connection from mRemoteNG shows no available Smart Cards in the logon screen (redirection not working?).

Usually (and in earlier versions), below "Steps to Reproduce" ended in connection being opened after step 3 and user presented with desktop of the remote machine.

## Possible Solution
Suspect redirection of Smart Cards is not working since the logon screen shows no available smart cards when clicking on the "smart card logon option" icon.

## Steps to Reproduce (for bugs)
1. Enable "Smart Cards" for Remote Desktop connection in connection options section "Redirect".
2. Connect to a Windows Server by opening the connection.
3. When prompted for credentials (using Network Level Authentication/NLA, not yet in Windows logon screen), choose Smart Card and type PIN and username hint.
4. Connection is opened, but Windows Server logon screen is displayed, no Smart Cards are available at the logon screen.

## Your Environment
* Version used: 1.77.0.41252
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 1803 x64

**Comment by sparerd** [comment]
@bluikko Is there anything in the log file? (https://mremoteng.readthedocs.io/en/latest/troubleshooting.html#logfile)

We haven't changed anything around the smart card redirect feature. We just pass the true/false value to the RDP client. Something may be failing and preventing that value assignment from happening. The log should hopefully have that info

**Comment by bluikko** [comment]
It looks like all sharing is not working. Clipboard does not work either to Remote Desktop.

Will try to log soon.

**Comment by bluikko** [comment]
I was mistaken in the message above - clipboard does work.

And after I checked the settings by disabling inheritance + enable smart card and clipboard in host settings, now smart card seems to work also?

I was sure that I especially tested this by disabling inheritance and set "Yes" to the individual host settings.

Not sure what happened. It may have been my mistake. This issue can be closed as invalid then...

**Comment by bluikko** [comment]
One last thought - was something changed regarding inheritance? I have a feeling that the issue was due to inheritance. Things used to work, but now work only after setting inherit: no and set the redirection for each host.

**Comment by sparerd** [comment]
I can do some further testing with inheritance. I know we've had some other complaints about it but I've never been able to replicate.

**Comment by bluikko** [comment]
I think what may have happened is that inheritance from a folder to individual connections under that folder was broken/folders had their "Redirect" settings reset.

I have some folders set to "SSH version 2" and some to "RDP". Both of these were configured to redirect Smart Card and Clipboard.

Then at one point redirection stopped working on all RDP connections. I now fixed them by going to each folder and set the Smart Card and Clipboard to "yes". Those that had been set to "SSH version 2" were now changed for a short time to "RDP" and set the redirect options, and changed back to "SSH version 2". Now everything works like before again.

Since I found the problem/workaround, everything is OK now.

**Comment by bbbuch** [comment]
The problem is actual for me too
mRemoteNG-Portable-1.76.20.24669 - smart card works fine
mRemoteNG-Portable-1.77.0.41307 - smart card does not works 

The same problem with disks.
workaround from bluikko doesn't help



Log:
2019-07-25 10:37:18,007 [1] INFO  - mRemoteNG 1.77.0.41307 Портативная версия starting.
2019-07-25 10:37:18,016 [1] INFO  - Command Line: I:\mRemoteNG\mRemoteNG.exe
2019-07-25 10:37:19,219 [1] INFO  - Майкрософт Windows 10 Корпоративная  64-bit
2019-07-25 10:37:19,222 [1] INFO  - Microsoft .NET CLR 4.0.30319.42000
2019-07-25 10:37:19,222 [1] INFO  - System Culture: ru-RU/русский (Россия)
2019-07-25 10:37:19,223 [1] INFO  - Checking FIPS Policy...
2019-07-25 10:37:19,224 [1] INFO  - Checking Lenovo AutoScroll Utility...
2019-07-25 10:37:19,362 [1] INFO  - Loading External Apps from: I:\mRemoteNG\extApps.xml
2019-07-25 10:37:22,519 [1] WARN  - PuttySessions.Watcher.StartWatching() failed.
Не найдено 
2019-07-25 10:37:22,519 [1] WARN  - XmingPortablePuttySessions.Watcher.StartWatching() failed: 'sessions' does not exist.
2019-07-25 10:37:46,905 [1] INFO  - Настройка переключения консолей для RDC 10.0.18362.
2019-07-25 10:37:46,910 [1] INFO  - Шлюз Служб терминалов поддерживается.
2019-07-25 10:37:47,205 [7] INFO  - Saving connections...
2019-07-25 10:37:47,576 [1] INFO  - Журнал подключений
2019-07-25 10:37:47,577 [1] INFO  - Подключение к системе "dc" через "RDP" созданого пользователя "test" (Описание: ""; Пользователь: "")
2019-07-25 10:37:48,536 [7] INFO  - Successfully saved connections

**Comment by GurliGebis** [comment]
I have found the code causing the problem, see the git bisect in here: #1713
