### ISSUE TITLE
anydesk via mremoteng portable with user and password

### ISSUE THREAD

**Issue by kal10bach** [mRemoteNG/mRemoteNG#1527]
hi, i'm using mremoteng over years now as a mangement-tool stored on a dropbox-account to access my anydesk-hosts. via external applications it's possible to provide the username but not the password. getting this to work would enable to sync the whole mremoteng-config and stored hosts to another pc and use them parallely
thx
## Expected Behavior

provide stored password
## Current Behavior

if i use these parameters in combination -> %USERNAME% %PASSWORD% -> user- / hostname anydesk is changed to the stored password
with only the username parameter it works, but requires manually password input
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by farosch** [comment]
- What version of mRemoteNG are you running?
- What operating system version are you running?
- Whats the configuration of your external tool? (Post your `extApps.xml` here)
- Using the password as a paramter is already possible, see https://mremoteng.readthedocs.io/en/latest/howtos/external_tools.html
- Does your command work when being run from a normal command prompt and not from within mRemoteNG?

**Comment by farosch** [comment]
Closed due to OP not responding

**Comment by Eagle3386** [comment]
Sorry for resurrecting this old issue, but since I came across this topic, others might as well, so here's how to solve the OP's issue..

AnyDesk's [Command Line Interface](https://support.anydesk.com/Command_Line_Interface) states that the password must be passed via pipe like this:
`echo password | "C:\Program Files (x86)\AnyDesk\AnyDesk.exe" alias@ad --with-password`

Note: In my case, I had to replace `alias@ad` with the actual ID to get it working.

For quick "copy-pasters":

- Display Name: `AnyDesk`
- Filename: `pswh.exe`
- Arguments: `-WindowStyle Hidden -Command "'%PASSWORD%' | &'C:\Program Files (x86)\AnyDesk\AnyDesk.exe' %USERNAME% --with-password"`

Note: The added `--plain` at the end helps to get rid of the (IMHO nothing but awful) UI as much as possible.

**Comment by achtvrv** [comment]
Hi all! Time is running! The solutions work! Thank you!
