### ISSUE TITLE
mRemote completely frozen after reboot or undocking laptop

### ISSUE THREAD

**Issue by 3f0102fd9d3862ea** [mRemoteNG/mRemoteNG#1534]
## Expected Behavior
mRemote should work.?
IT should allow you to click new on a panel and start up without having to be killed and then rebooting the system.

## Current Behavior
Splash screen appears and the new connection panel window appears. Frozen/locked at this point. Even ending task doesn't resolve the issue it happens again after restarting the program.

## Steps to Reproduce (for bugs)
Reboot computer or disconnect from a docking station. Start mRemote.

## Context
It has affected me in that mRemote is useless. Also why is this 32bit? There is absolutely no reason for programs not to be 64 bit in this day and age.

## Your Environment
Windows 10 Enterprise version 1803 os build 17134.885 64bit.

**Comment by farosch** [comment]
Please update to the latest Windows 10 1903 with all patches.
Your issue may already have been solved. See #1487 and #1343

**Comment by farosch** [comment]
What Version of mRemoteNG are you running?
Please provide a log file and a dump. See: https://mremoteng.readthedocs.io/en/latest/troubleshooting.html

> IT should allow you to click new on a panel and start up without having to be killed and then rebooting the system.

What does this sentence even mean?

> Reboot computer or disconnect from a docking station. Start mRemote.

This can definitively not be true, otherwise nobody would be able to use mRemoteNG **ever**.

> Also why is this 32bit? There is absolutely no reason for programs not to be 64 bit in this day and age.

Just a few of those reasons you think don't exist:
- We are shipping in 32bit because the Citrix client is only available in 32bits
- Just because your system is 64bit doesn't mean all others are
- This software won't get more productive just by being run in 64bit. This is just not a high priority
- This software is being developed in our spare time and I only have so much time to think about 64bit builds as you have for writing issues 😝 
- ...

**Comment by farosch** [comment]
Closed due to OP not responding
