### ISSUE TITLE
MRemoteNG does not appear on taskbar

### ISSUE THREAD

**Issue by ktn01vd** [mRemoteNG/mRemoteNG#1560]
mRemoteNG does not appear in the task bar when it is open in a screen that is not the main screen. I have to move MremoteNG on the main screen so that it appears in the taskbar. I can then put it back on a secondary screen without it disappearing from the taskbar.

Steps to Reproduce
1. start mRemoteNG
2. Put it on a secondary screen
3. Close mRemoteNG
4. Start mRemoteNG. it start on secondary screnn ans does not appears on taskbab
5. Move mRemoteNG on main screen. It appears on taskbar.
6. Move it back to a secondary screen. It stay on taskbar.

## Your Environment
* Version used: 1.76.20.24669
* Operating System and version: Windows 10 Entreprise 1809 x64, 3 monitors

**Comment by ktn01vd** [comment]
Related to issue 1531 ?

**Comment by farosch** [comment]
This is working absolutely fine for me. I am using three displays with 2 virtual desktops and all three possible scenarios are working just like expected. Only difference is I am using Windows 1903...

What option do you have set in the settings app?
![image](https://user-images.githubusercontent.com/22905106/64536082-bfad6b00-d318-11e9-9c63-faf4b45bf94f.png)

**Comment by ktn01vd** [comment]
Hello,
here is my config:
![image](https://user-images.githubusercontent.com/54936312/64589650-ea91d080-d3a5-11e9-87ff-67b4e4326771.png)

I have tried to change my config like yours but I still have the same problem.

I am working with my desktop screen on left and two external screen. The main screen is the external screen on the middle.

I am not sure if this problem appears after a mRemoteNG upgrade or a Windows patching.

Thanks

**Comment by farosch** [comment]
Hey @ktn01vd 
I've been trying this out on a bunch of different systems with different settings but I have never been able to replicate the behaviour you described.

- Are you using any third party software, that could interfere with mrng/the taskbar?
- Also: Would you be able to update your system to the latest Windows 10 to make sure this isn't caused by Windows itself? Latest Windows version should be sth like this:
![image](https://user-images.githubusercontent.com/22905106/65487965-4aa96c00-dea8-11e9-990a-18cac8106489.png)

**Comment by farosch** [comment]
Closed due to op not responding
