### ISSUE TITLE
Copy/paste doesn't work from/to pc to rpc. I have mRemoteNG version 1.77.0.41252.

### ISSUE THREAD

**Issue by jcsanchezrb** [mRemoteNG/mRemoteNG#1562]
I can't copy/paste from PC to rpc and also from rcp to pc.
If I try to do this from mstsc, I can copy and paste without any problem.

**Comment by farosch** [comment]
I'm guessing what you want to say is: "copy/paste not working in rdp"?
If so have you enabled clipboard redirection on that connection?
![image](https://user-images.githubusercontent.com/22905106/64366704-1106e300-d017-11e9-933e-006f8370d222.png)

If I misunderstood you then please take the time to file a proper issue, the template we provide is there for a reason ;)

**Comment by jcsanchezrb** [comment]
Thank you very much for your support.

**Comment by karlochacon** [comment]
is there a way to have clipboard to true as default? Instead of enable by connection? Like global setting o make it by default in the tool for next version?

thanks a lot

**Comment by St1ckyGreeN** [comment]
if you are too lazy to enable clipboard in every single rdp setting like me (i have like 300 rdp connections in MRemote -.-
then do this:
go to file-> export your config
open config with notepad++
goto seach->replace
search for: RedirectClipboard="false"
replace with: RedirectClipboard="true"
enable "search for whole word" check mark
click "replace all"
save config
import in MRemote
->there u go!

**Comment by lunarRover986** [comment]
@CarlosJoseChaconChavarria 
> is there a way to have clipboard to true as default? Instead of enable by connection? Like global setting o make it by default in the tool for next version?
> 
> thanks a lot

i don't know when they added that but there are default settigs and default inheritance in addition to the connection settings and connection inheritance but I didnt't really figure how they work so far because they default settings and inheritance dont't seem to get inherited to all present connection when I change something at the defaults.

Edit: You also need to apply the default settings manually to every folder/connection for them to work!
