### ISSUE TITLE
mRemoteNG 保存用户登录信息中的密码是加密的？

### ISSUE THREAD

**Issue by 359193585** [mRemoteNG/mRemoteNG#1563]
## Steps to Reproduce (for bugs)

1.mRemoteNG 保存用户的登录信息中的密码是加密保存的？是统一的算法吗？安全性如何？密钥是否可以自定义？
2.建议mRemoteNG软件的增加使用软件密码登录功能，以便杜绝无关人员登录软件访问远程服务器。
3.保存到数据库中的登录信息，如果需要让多个维护人员共享时，除了配置中的数据库连接的限制外，能否增加权限管理，让部分用户只能访问被授权能访问的服务器。

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by farosch** [comment]
> 1) mRemoteNG Save the password in the user's login information encrypted? Is it a unified algorithm? How safe is it? Is the key customizable?

The password is stored encrypted with a default key! You need to set a password on the connections file to ensure that connections are being encryptet using a unique key.

> 2) It is recommended to use the software password login function to increase the mRemoteNG software, so as to prevent the unrelated person from logging in to the software to access the remote server.

Yes, see 1) It's also good practice to enable this setting:
![image](https://user-images.githubusercontent.com/22905106/64418304-09891d80-d09b-11e9-88c0-341027060df9.png)

> 3) Save the login information to the database. If you need to let multiple maintenance personnel share, in addition to the limitations of the database connection in the configuration, can you increase the rights management so that some users can only access the servers that are authorized to access.

This is currently not possible. Please open an issue if you want this to be implemented.

**Comment by 359193585** [comment]
我的第二问题你理解错了，我不是指个性化加密联系信息。 我的意思是建议eRemoteNG这个软件自己在启动后，增加一个软件打开运行时的密码登录功能，防止有人使用我的电脑时，运行这个远程管理软件，访问了他不该去访问的服务器

**Comment by farosch** [comment]
@359193585 What do you mean by recommended? mRemoteNG simply does not have such a function, thus we cannot recommend it :D
My personal recommendation is to simply lock your PC whenever your not using it.
If you feel like this should be implemented then please open an issue asking for this explicit feature.

Also please always post in english! You can use some kind of translate software for this but it's much simpler if you post it in english instead of having everyone that wants to read this have to translate it first. The more people can read your posts the more will/can help you!

**Comment by 359193585** [comment]
Thank you, I didn't expect someone to answer the question so soon.
Not everyone has a strong safety awareness of using passwords to protect their personal computers in China.

recommended?  I  means suggestions，not  recommend. It's an error of translate.
Thanks you again for your professional answer.
