### ISSUE TITLE
Suggested BeyondTrust settings for MRemoteNG

### ISSUE THREAD

**Issue by itdraftsman** [mRemoteNG/mRemoteNG#1593]
## Expected Behavior
We've employed the BeyondTrust Privilege Management (formerly known as Avecto)in "High Flexibility" mode in our environment, and we've seen several developers unable to run MRemoteNG as either Administrator or while allowing any child process from the executable. Expected behavior is for MRemoteNG to be able to run as if there are no restrictions on Administrative functions.

## Current Behavior
When BeyondTrust is allowing any child process of MRemoteNG, MRemoteNG.exe then becomes suspended after attempting to access the Microsoft.NET framework and triggers the Windows Error Reporting service.

## Context
Please provide any advised BeyondTrust settings that you would deem necessary, or inform if we need to contact BeyondTrust to resolve this issue.

## Your Environment
User's computer is running Windows v1803 with BeyondTrust Privilege Management (user is not enabled as Administrator account)

**Comment by farosch** [comment]
As the goal of BeyondTrust seems to be to increase security I am kind of baffled to see that your clients are running Windows 1803. My first advise would be to update your clients - Maybe the problem will disappear after an update as you already said yourself that this is only happening for some developers and not for all.
Secondly I would try to obtain any log files from clients/BeyondTrust and show them to the BeyondTrust support. They will then be able to analyze these log files and decide if this is a problem that they will need to handle or ideally point us to the issue in mrng so that we can fix it.
You should also provide the mrng logfile/dump to us, maybe we are able to detect the issue by ourselves.
See here on how to do that: https://mremoteng.readthedocs.io/en/latest/troubleshooting.html

**Comment by farosch** [comment]
Closed due to OP not responding
