### ISSUE TITLE
1.76 v. 1.77 rdp clip

### ISSUE THREAD

**Issue by jbruns2019** [mRemoteNG/mRemoteNG#1652]
clipboard activity between windows server and windows client does not work
## Expected Behavior

copied data from server or wkstn should be pasteable on server/wkstn
## Current Behavior

clipboard not updated
## Possible Solution

it works fine in 1.76.  Start looking at 1.77 and figure out what change you did that broke it.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by revuwa** [comment]
Had the same issue after updating to v1.77.1.

But it seems to be just a new implemented setting since v1.77 (https://github.com/mRemoteNG/mRemoteNG/pull/951) which brings an optional clipboard redirection for RDP.

Switching that setting: configuration -> redirect -> clipboard to yes, should do the trick.

**Comment by farosch** [comment]
@jbruns2019 Since version 1.77 there is a seperate setting for clipboard redirection.
You have to enable it, just as @revuwa said.

**Comment by JoeBrunsTR** [comment]
Is that option on the Tools > Options someplace?

**Comment by farosch** [comment]
@JoeBrunsTR 
Check the `Clipboard` option in the `Redirect` section of the connection properties:
![image](https://user-images.githubusercontent.com/22905106/128106124-c842c1ec-52d5-4573-8536-c4a752ae4a75.png)
