### ISSUE TITLE
mremoteng.org domain issues

### ISSUE THREAD

**Issue by acederlund** [mRemoteNG/mRemoteNG#1677]
Hi,

I'd just wanted to inform you that the mremoteng.org domain has expired since a couple of days ago:
Domain Name: MREMOTENG.ORG
Registry Domain ID: D158001395-LROR
Registrar WHOIS Server: whois.google.com
Registrar URL: https://domains.google.com
Updated Date: 2020-01-22T20:32:16Z
Creation Date: 2010-01-07T18:50:48Z
Registry Expiry Date: 2021-01-07T18:50:48Z

/Andreas

EDIT: Mixed up the WHOIS info with the error message I got when browsing the website..

**Comment by KevinNSTA** [comment]
The registry Expiry date shown there says 1-7-202**1** not 2020


However, it looks like the Nameservers have changed from Cloudflare to Google for some reason yesterday
![image](https://user-images.githubusercontent.com/60158736/73008745-35543800-3ddd-11ea-8c2f-00658339a723.png)
![image](https://user-images.githubusercontent.com/60158736/73008794-53219d00-3ddd-11ea-8105-ef3ea1746ac4.png)

**Comment by PsychoData** [comment]
The registry Expiry date shown there says 1-7-202**1** not 2020


However, it looks like the Nameservers have changed from Cloudflare to Google for some reason yesterday
![image](https://user-images.githubusercontent.com/60158736/73008745-35543800-3ddd-11ea-8c2f-00658339a723.png)
![image](https://user-images.githubusercontent.com/60158736/73008794-53219d00-3ddd-11ea-8105-ef3ea1746ac4.png)

**Comment by PsychoData** [comment]
@benwa @farosch @kmscode @sparerd 
One of you have access to the public DNS to fix it?

**Comment by benwa** [comment]
I don't have DNS access, but am aware of the issue. Will try to get it resolved asap

**Comment by acederlund** [comment]
My apologies, I didn't look at the right WHOIS information, and went on the error message that I when browsing the domain :( Glad it's being looked at tho!

**Comment by kmscode** [comment]
Hi everyone - sorry for being MIA. Life has been getting in the way.

It looks like I have access to basically everything except DNS... I've contacted @sparerd directly via e-mail - I thought I had his phone number but can't find it immediately. I'll give him a bit to respond via e-mail either way.

Stay tuned and sorry for the inconvenience.

**Comment by kmscode** [comment]
OK... So a quick update... who.is shows the correct DNS server (cloudflare) but Cloudflare (which I have access to) isn't the registrar for the domain (who.is says it's google which I don't have access to and cloudflare says the registration is unknown).

Cloudflare also notes that the expiration of the domain is 1-7-202**1**... :confused:

**Comment by PsychoData** [comment]
So per that Whois I showed above, the registrar is Domains.google.com - at that registrar, you can change the public DNS Servers to be something other than Google if desired. 

However, if the NS records are at another DNS provider than Google, then it won't let you create records in Google's system

Maybe someone ended up at domains.google.com, tried to create a DNS record, and accidentally hit the prompts to yank the NS records back to domains.google.com 

If so, then you need to get the DNS aimed back at the cloudflare Nameservers, so cloudflare can server the records 

and you would also want to add any records someone created at the domain.google.com to cloudflare.

**Comment by kmscode** [comment]
DNS records are at Cloudflare and they look good. So updating the registrar (google) info with the correct name servers should take care of this...

As far as the "expired" confusion... Before we moved over to GH Pages, I think we hosted on Google... So it's possible that the the expired message is referring to the hosting rather than registration - just a guess...

**Comment by sparerd** [comment]
Hey all, sorry for the confusion. This was a domain name expiry issue. We currently purchase through Google, but do all NS config via Cloudflare since (at the time at least) they were the only way to get proper TLS encryptions on custom domain websites hosted on Github. I've corrected the payment issue with Google (stupid expiration date changed on the credit card).

I have not been able to load the site since correcting the domain, but Cloudflare is showing successful page loads now. I'll continue trying the site tonight.

Sorry for the inconvenience, everyone. Thanks to those of you who reported/helped with triage.

**Comment by sparerd** [comment]
Was just able to load the site. If you are still unable to load the site, give it some time for your DNS provider to update their records.
