### ISSUE TITLE
“Missing the DataColumn 'UseEnhancedMode' ” this problem still exists in the 1.77.1.27654 version

### ISSUE THREAD

**Issue by 9raxdev** [mRemoteNG/mRemoteNG#1730]
I want import configs from xml to mysql ，It got an error

win10 LTSC
mysql 5.6

![image](https://user-images.githubusercontent.com/11805413/78846952-0181c980-7a40-11ea-9136-ca89bff7a02f.png)

**Comment by spiorf** [comment]
A workaround is to delete the column.

I do not see any "Use enhanced mode" setting in the gui, so i assume that it was removed some time ago, and the sql creation scripts were not updated.

**Comment by farosch** [comment]
There is an enhanced mode available when using vmid
![image](https://user-images.githubusercontent.com/22905106/82766211-5ffedd80-9e1d-11ea-9b01-84f8be596d8c.png)
@9raxdev is running a developer preview version instead of the stable version.
Things like that can happen, this is why you use stable builds as a normal user...
