### ISSUE TITLE
Crash mRemoteNG work with two monitors

### ISSUE THREAD

**Issue by dmalyshok** [mRemoteNG/mRemoteNG#1745]
## Steps to Reproduce (for bugs)

1. Work with mremote on extended monitor
2.  Disconect  extended monitor
3. Mremote  -> do reconect
4. Crash

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by Benchwork** [comment]
just for clarification, the extended monitor is on your computer and not the remote computer correct?   also can you tell me how the monitor was connected?  eg. hdmi/displayport/usb-c/RGB

thank you

**Comment by dmalyshok** [comment]
RGB
yes work with two local monitors

<blockquote class="imgur-embed-pub" lang="en" data-id="a/tRd0D8z"><a href="//imgur.com/a/tRd0D8z"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>


thank you for replay

**Comment by Benchwork** [comment]
does it actually crash or just disappear off the screen and become unusable?   if I am using mRemoteNG on my 2nd screen and I disconnect it, some times it seems like mRemoteNG Stays in the same place instead of getting adjusted to to the new screen layout. 
![image](https://user-images.githubusercontent.com/7304823/81300177-54519f80-9045-11ea-85f1-08974211044b.png)
 when this happens, I then have to shift+right-click on mRemoteNG  and click on move, 
![image](https://user-images.githubusercontent.com/7304823/81299432-36376f80-9044-11ea-85c4-ee789918ad4e.png)
  (your mouse will change to a 4-way arrow) 
![image](https://user-images.githubusercontent.com/7304823/81299454-3fc0d780-9044-11ea-82ed-bbeaa88ca621.png)
 and then use arrow keys to move it into the screen. in my example I would use the left arrow key.

this is not a fix its a workaround for my issue, not sure if that helps.

**Comment by farosch** [comment]
Most likely not related to mRemoteNG but your graphics driver / dockdriver / windows version used.
We had issues like these before: #1592 #1343
Unfortunalety you failed in including any kind of relevant information, that's why I will close this issue.
If you decide to fill in a proper issue or update this one with the needed information we will be glad to help you ;)
