### ISSUE TITLE
Is mRemoteNG dead?

### ISSUE THREAD

**Issue by GeriZ** [mRemoteNG/mRemoteNG#1823]
I see no further development since 2019. Is mRemoteNG dead?

**Comment by VShawn** [comment]
mRemoteNG is a large scale project, that means it is hard to add any new feature. And once a new feature added, the software needs a full-test for preventing bugs, that's why development going slow.

BTW, there are new features add in [pull requests](https://github.com/mRemoteNG/mRemoteNG/pulls)
new plan for V1.78 in [project](https://github.com/mRemoteNG/mRemoteNG/projects/4#card-38823598)
you can go and check by yourself

**Comment by farosch** [comment]
> I see no further development since 2019. Is mRemoteNG dead?

That's more of a problem with your eyes than the project itself ;)
![image](https://user-images.githubusercontent.com/22905106/88462102-2132e580-cea9-11ea-9dcd-e0f570361bfa.png)


BTW: This is the second time I hear this question. Any open source project is only as much alive as it's community!
If development has slowed down too much for you - PARTICIPATE!
