### ISSUE TITLE
best option for search

### ISSUE THREAD

**Issue by christiandef** [mRemoteNG/mRemoteNG#184]
Hi, sorry for my english
it will be better if the search method include search by ip & name host , and highlight the result in the connection panel
I think this would accelerate the search

Best Regards.

Christian Bustos

**Comment by peterchenadded** [comment]
I second this request but also to search the description field.

Looking at the code it seems to be pretty achievable.

**Comment by peterchenadded** [comment]
Will see if i can make the changes myself

**Comment by kmscode** [comment]
@peterchenadded That would be fantastic! Feel free to submit a pull request if you are able to do this:
https://github.com/mRemoteNG/mRemoteNG/blob/develop/.github/CONTRIBUTING.md 

This would be a perfect fit for some other planned changes that we want to include in 1.76 (see #338).

**Comment by sparerd** [comment]
Thanks to @peterchenadded for providing the PR for this issue! This will be available in v1.76

**Comment by peterchenadded** [comment]
No worries,

Is there also any work on a centralised credentials manager which stores
all the credentials and the connections can just reference the data that's
available there?

The folder inheritance based approach at first is a good idea but becomes a
nightmare to maintain, due to the credentials been duplicates for some
folders.

I could a popup like that appearing in visual studio is that for the same
purpose?

Cheers,

On 28 May 2017 12:33 PM, "David Sparer" <notifications@github.com> wrote:

Thanks to @peterchenadded <https://github.com/peterchenadded> for providing
the PR for this issue! This will be available in v1.76

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mRemoteNG/mRemoteNG/issues/184#issuecomment-304488713>,
or mute the thread

**Comment by sparerd** [comment]
Yes, we are working on a credential manager for v1.76. A preview is available already on the develop branch

**Comment by peterchenadded** [comment]
Awesome! looking forward to it. If you need help testing it, am good for it.

Cheers

On 29 May 2017 11:51 PM, "David Sparer" <notifications@github.com> wrote:

Yes, we are working on a credential manager for v1.76. A preview is
available already on the develop branch

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mRemoteNG/mRemoteNG/issues/184#issuecomment-304665911>,
or mute the thread
