### ISSUE TITLE
Can't export specific folder (xml)

### ISSUE THREAD

**Issue by minishadows** [mRemoteNG/mRemoteNG#194]
Hello,

I'm trying to export specific folder in my mRemoteNG tree structure into xml file.
To do that, I clic right on my folder and "Export to file..."
I use option "Export the currently selected folder" and all option in "Export Properties"
Here is my issue : I have nothing in my xml export, only that :

<?xml version="1.0" encoding="UTF-8"?>
<Connections ConfVersion="2.5" Protected="xrvPPd+f9+E04EL+SFv0qsrnMLoAlH7bo3U8/kBG2vfeJIuFqFbI/OFr0LRa+H80" Export="True" Name="mR|Export (20161024 10:29:46)"/>

My mRemoteNG version : 1.74.6023.15437
I try to do the same export in CSV format and it's ok.
I would like to do this kind of export in XML to be import in old mRemoteNG version (csv isn't implemented)

Thanks in advance for your help
Regards,
Emilie

**Comment by kmscode** [comment]
From https://mremoteng.atlassian.net/browse/MR-876:

When exporting files from connection list you are asked to export items: Export Everything, Export currently selected folder, export currently selected object.

- If selecting folder, does not export any contents of the folder and only folder itself.
- If you have multiple connections in a single folder, cannot mass export and must export them one at a time. No ability to multi select connections in folder and export all those in a single export file. CTRL+Click and SHIFT+Click not accepted for multi select.
- If you choose "Everything", export will create xml of the entire connection list including items above selected object int he hierarchy tree as well as below and in selected folder as well as all other folders on same level.

Expected behavior would be to have "everything" export folder and all subfolders and connections in them but remain in the selected folder. If you choose the very most top level (connections) it would export all subfolders and connections. If you chose 1 level down, it would export that folder and all connection below it, staying inside of the original selected folder.

**Comment by minishadows** [comment]
Hello,

So it's a bug ?
In previous version (1.72.5065.32737) this kind of export was working.
I could export one folder and it content only with those steps :
- clic right on the folder
- export xml
Currently we can't do that on 1.74 release ?

Regards
Emilie

**Comment by sparerd** [comment]
Tested exporting a folder (and its contents) in v1.75 beta1 and it's working as expected. I think we will be releasing 1.75 beta 2 soon - once that is out I'd recommend testing with that version. (However, 1.75 introduced some new configuration file properties. These are not backward compatible with previous versions.)

**Comment by minishadows** [comment]
Hello,
I tested with 1.75 beta 3 and it's working now
Thanks for the support :)

Regards
Emilie

**Comment by ehmidH** [comment]
I exported the folder that I want with multiple connections. Then I edited in Visual Studio Code and removed the connections that I don't want.

**Comment by simonai1254** [comment]
I'm not sure, but I think this feature is working with 1.77. I guess this issue can be closed... 

Edit: Noted that this issue is already closed :D
