### ISSUE TITLE
latest update removed "Quick Connect" panel for selecting quick connection type

### ISSUE THREAD

**Issue by kmscode** [mRemoteNG/mRemoteNG#197]
|  |  |
| --: | --- |
| Operating system | Windows 7 x64 |
| mRemoteNG version | 1.73 Beta 2 |

In prior version of mRemote, when typing a host into quick connect and pressing enter, there was a panel at the bottom that allowed you to tab to the correct type of connection - making it very useful to type hostname, enter, tab to SSH2, RDP, VNC etc. 

![image](https://cloud.githubusercontent.com/assets/16654335/19664635/5877ce66-9a0f-11e6-8d12-563745b9065e.png)

**Comment by sparerd** [comment]
I think this one was removed in v1.73 (unreleased) which then got rolled into the v1.74 release when we took over the code base from the previous maintainer. I know a few folks have asked about it.

I have no issue with bringing it back, though I would like to give users the option between the pop-up and drop-down selection styles. Something in the options pages to control it maybe?

**Comment by kmscode** [comment]
This is different. See the quick connect panel at the bottom? That's missing. Basically once you hit enter from the quick connect text box in 1.72, that panel pops up with focus allowing you to tab to the connection type and hit enter again to connect. 

I just copied and pasted the description from JIRA. I'll update accordingly...

**Comment by welbow** [comment]
Would love to see this feature return. It is very handy in heterogeneous environments for those who like to use the keyboard. And thanks to all for taking over the project!

**Comment by kmscode** [comment]
Scheduling for 1.76... @sparerd 's comments are accurate (I thought he was referring to something else initially). 

The overall design of the quick connect toolbar changed where it added a dropdown menu to select the session type. This panel was purposefully removed. Though, I can see how this would be more desirable. 

As @sparerd mentioned, we'll need to make some other design choices / options available to get the best of both worlds -- since the current dropdown menu is a very solid design, but not very intuitive for those that might rely more on keyboard input.

**Comment by songohan** [comment]
I also love to have this feature back. I work in a heterogeneous environment and I can't manage to have all ten thousand devices in my mRemoteNG configuration. So I use quick connect very often and it's a pain to always choose the connection type first (after all, the arrow for the dropdown is very small).
Suggestion 1: add a setting, in which the user specifies if he likes to choose the connection type before (dropdown) or afterwards (panel).
Suggestion 2: just change it back to the panel, because I can’t think of a real use case for the dropdown. If someone really wants to use the mouse, he can also click the connection type in the panel.
Thx

**Comment by pedro2555** [comment]
@kmscode Is this any different than pressing ENTER on that dropdown?

Because from what I can see that is the part missing, the ENTER functionality. The panel was replaced with the dropdown button, but the connect functionality never was.

So, __enter IP__ `TAB` __use selection keys to select protocol__ `ENTER`, and you're connected; is a bit different, I admit, but does the exact same thing using the exact same input, the keyboard.

**Comment by kmscode** [comment]
@pedro2555... This panel was remove for some different workflow in 1.73+ (what you see in the current UI). While I don't plan on putting back the same exact code/prompt, I was going to find a best of both worlds type of solution that would be more keyboard _and_ mouse friendly.

While the dropdown isn't bad, I can see the value in the panel. So (when I get around to this) the updated workflow would be more user friendly in either scenario...

**Comment by kmscode** [comment]
After reviewing #708 further... I think this is the best solution here (and it doesn't require a new panel either)...

The new workflow is as follows:
1. Type hostname
1. Press tab
1. Arrow down to select desired protocol
1. Press enter

**Comment by gwenherz** [comment]
Hi,
Any chance to see back this Quick Connect panel?

This feature is very usefull to select the proper protocol for devices...

Thanks in advance
