### ISSUE TITLE
How to SSH using signed public key?

### ISSUE THREAD

**Issue by dinbtechit** [mRemoteNG/mRemoteNG#1972]
Is there a way I can specify the "signed public key" while ssh'ing into a remote server? Currently there is not option in mRemote to specify public signed key nor in Putty.  Or is it something that has to be included in the putty project?

For example: Here is the raw ssh command
```
ssh -i ~/.ssh/id_rsa -i ~/Downloads/id_rsa.pub.signed username@192.168.17.8
```

## Context
unable to SSH into a remote server that uses signed public key. or openSSH.

**Comment by LIyoai** [comment]
You can use pageant.exe (an SSH authentication agent for PuTTY, PSCP, PSFTP, and Plink)
Add the key and add pageant.exe to your startup.
https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html

**Comment by dinbtechit** [comment]
Unfortunately pageant.exe doesn't accept a `signed public key`. Below is the error that I got.

![image](https://user-images.githubusercontent.com/17984781/122932844-75a64580-d344-11eb-9c2b-d29297c76096.png)

**Comment by farosch** [comment]
This is either a problem with you using a public key instead of a private one or the format of the key being wrong.
Read [this ](https://stackoverflow.com/questions/27129904/pageant-does-not-load-ssh-2-key-generated-with-gitbash) answer for more information on how to resolve your issue.
Googling your exact error message gives you a bunch of search results to go through.

Even if it is a bug, it cannot be fixed by mRemoteNG, as we completely rely on PuTTY for key authentication.
Please try your key in the latest PuTTY client. If it does not work, but you have verified that your key is OK, then file a bug at https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html. If it works in PuTTY but not in the latest mRemoteNG preview release, then please reopen this issue.
