### ISSUE TITLE
VNC shared option

### ISSUE THREAD

**Issue by Mac83** [mRemoteNG/mRemoteNG#198]
Hi,

I was looking the option "shared" in VNC connection but I didn't find it, could you add it ? It allows to have multiple connections opened on the same host.

I'm using VNC at work, and we are several people to access the same hosts with VNC. Without the "shared" option, you close etablished connections when you connect to a host, and it's annoying a lot for disconnected users.

I'm using realVNC and UltraVNC clients, and both have the "shared" option. But as I have to open several VNC connections I looked for a software that open connections in tabs, and mRemoteNG seems very good at it. The only drawback for me at the moment is this missing option "shared".

Do you plan to add it in a future release ?
Thanks

|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.74 |

**Comment by Benchwork** [comment]
I also use VNC at work ( UltraVNC ) and I understand your wanted outcome, however I have found that the setting that you are talking about "share the server" is an internal client feature to UltraVNC, and not implemented across all VNC clients.  there is also a setting on the servers that allows you to share a VNC server regardless of the clients connecting.

![image](https://cloud.githubusercontent.com/assets/7304823/19698719/70925872-9abe-11e6-87c9-5026107a595d.png)

this is what I use for all VNC servers, so that I can have multiple clients connect at the same time. we use the view only setting with another application (that doesn't have it implemented) for continuous monitoring of those stations, and I can still connect with mRemoteNG.  

I believe the Benefit of using the "share the server" is that it can conserve some bandwidth. but I'm unsure of that for a fact. 

I hope this helps.
Peter C.

**Comment by Mac83** [comment]
Thanks for your answer, I didn't thought it was a specific option of some VNC servers and clients. Now I understand why this option is not present in mRemoteNG.

I had a quick look at our different VNC servers, as we have windows, Linux and HPUX hosts, and it seems they all have the option to threat new connections as shared. I'm gonna use this server parameter as far as I can.

And for servers I can't modify configuration, I achieved to use external client and integrate it in mRemoteNG, but it takes a few seconds to capture the window and put it in a tab. If it works like this for few servers, it's acceptable for me.

Thanks again
