### ISSUE TITLE
Return splited wing for connection and it's configurations, as v 1.76.20

### ISSUE THREAD

**Issue by Apollon-Theos** [mRemoteNG/mRemoteNG#1983]
Better splitted wing, because I can click on server look at it's config, click next server and so on.

## Expected Behavior
I I edit config for connection, and user ask me some questions, return to editing need switch ti list of server and switch again to editing. Uncomfortable.

## Current Behavior
List of server and config divided to separated tabs.

## Possible Solution
return view as 1.76.20, but with new theme from 1.77.2

## Steps to Reproduce (for bugs)
1. View and work
2.
3.
4.

## Your Environment

* Version used: 1.77.2nb 24062021
* Operating System and version: Windows Server 2019

**Comment by bereldhuin** [comment]
+1
Previous vertical split between connections and configuration is easier than swtching between panels.
Maybe we should have small buttons to quickly hide and show configuration panel when not used.

**Comment by ErMaqui** [comment]
These configuration are possible on 1.77. I have it working.

But, I doesn't know if you need to move the tab or if they only works if you update from previous version.

**Comment by Apollon-Theos** [comment]
It's work, but never described until your answer. Self find this options is non-possible.

!!! Detachable panels are EVIL !!!

I'm understand, you learn new features of framework, but not all features needed in real work.

**Comment by bereldhuin** [comment]
Yes, thanks ! Really touchy.

1/ detach the config panel by dragging the panel link to the main screen until the panel is floating
2/ Move the panel above the connection panel and move it gently (just under the vertical center) until a blue mask indicates its future position.

**Comment by Apollon-Theos** [comment]
Why this design not "by default" ? Migrate to new version of mRemoteNG it would be easier.

**Comment by LIyoai** [comment]
Keep Config & Connnections Panels Together When Hidden #1406

**Comment by farosch** [comment]
Already possible.

**Comment by simonai1254** [comment]
> Already possible.

Yeah it is possible to align the panels as they were in the previous version, but it requires tinkering (as I found out during testing and as stated above by @bereldhuin). 
Just because _it works_ does not mean it's user friendly, and I share the opinion that the default view should be having each panel top/bottom and not in an overlay. I will check again tomorrow how it behaves when upgrading, if the change is only for new installs then I can live with it. But in case I need to manually change it even when upgrading imho this reduces the usability quite a bit. 

I don't request to change it immediately, though I'd like you to consider the above stated points and reconsider it for implementation soon. 

Thanks once more for everyone that helps to make this software better than it already is and have a great day

**Comment by simonai1254** [comment]
Okay just tested it: When migrating from 1.76.20 the stacked windows are kept as they were, with a fresh install the config is on top of the connection.
I my point of view here the default should be changed to match the legacy design.
