### ISSUE TITLE
Sql upgrade script to 1.77.2

### ISSUE THREAD

**Issue by kramttocs** [mRemoteNG/mRemoteNG#2214]
Currently on 1.77.1 using Sql Server.
Is there an upgrade script to migrate the db to 1.77.2 or does it need done manually?

**Comment by simonai1254** [comment]
I strongly assume that the SQL backend was not touched in this version upgrade and you should be able to just continue to use the SQL-Server without any migration. 

The [Changelog](https://github.com/mRemoteNG/mRemoteNG/blob/v1.77.3-dev/CHANGELOG.md) has only one entry regarding SQL:

#1589: [FIX] Update SQL tables instead of rewriting them

You should be able to upgrade straight away.

**Comment by Kvarkas** [comment]
Currently no changes in sql side, but in 1.77.3 I am reworking options so a lot of changes coming and due that is delay with nb release :(

**Comment by kramttocs** [comment]
I had tried it in the past and just did again but when trying to connect 1.77.2 to a restored backup of a 1.77.1 db I get:
![image](https://user-images.githubusercontent.com/11565750/166066449-4cea3831-2ecf-449a-be2f-3115acce1651.png)

I believe when I had tried previously I added the column but then I got another missing one

**Comment by kramttocs** [comment]
I went through and updated/added the new columns but now am getting:


![image](https://user-images.githubusercontent.com/11565750/166074956-6c9b9f34-7c6c-434c-8faa-713871cc25e8.png)

Looks like it's happening with:
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[tblCons]') AND name = 'StartProgram')
BEGIN
 ALTER TABLE tblCons ADD StartProgram varchar(512), StartProgramWorkDir varchar(512);
END;GO;
ALTER TABLE tblRoot MODIFY COLUMN ConfVersion varchar(15);GO;

Is 'Modify' valid for SQL Server?

**Comment by kramttocs** [comment]
This can be closed. Rather than trying to upgrade the existing db, I just moved all the data to a clean new db.
Thanks!
