### ISSUE TITLE
Allow FIPS to be enabled

### ISSUE THREAD

**Issue by kjesso** [mRemoteNG/mRemoteNG#222]
I copied this request from the [original post](https://mremoteng.atlassian.net/browse/MR-637) on the mRemoteNG Atlassian bug/feature tickets site. Our environment for security reasons must have the FIPS windows setting set to Enabled. I can use Windows Remote Desktop to any of our servers fine (I have the latest RDP version 8.1 installed), but when launching the latest version of mRemoteNG (Prerelease 1.75 Alpha 3) I get the following message:

> The Windows security setting, "System cryptography: Use FIPS compliant algorithms for encryption, hashing and signing", is enabled. This setting is not compatible with mRemoteNG.
> 
> See the Microsoft Support article at http://support.microsoft.com/kb/811833 for more information.
> 
> mRemoteNG will now close.

In most applications, if an application is not FIPS compatible, it can be used by creating a .config file and putting the following in:

```
<runtime>
<enforceFIPSPolicy enabled="false"/>
</runtime>
```

However, when putting this in the proper format, the application still does not run due to FIPS and then closes. FIPS check is hard coded in. The check should be soft coded as the .config file will allow the use of non Fips crypto's, even if Windows as a whole does not allow it.

**Comment by veeramarni** [comment]
Any ETA for this fix? I can't use it because of it.

**Comment by veeramarni** [comment]
Can you guys tell us whats involved in fixing this issue? Unfortunately, due to our latest security safeguards, FIPs need to be enabled in our machines and this would cause the program to fail.

**Comment by pedro2555** [comment]
Not much time to look at this at the moment.

But you may check https://github.com/mRemoteNG/mRemoteNG/blob/v1.75Hotfix8/mRemoteV1/App/CompatibilityChecker.cs, if you want to get an insight of exactly why you are getting that message; maybe you can work around it for the time being.

**Comment by veeramarni** [comment]
@kjesso wondering if you were able to workaround with this issue? Feel like I'm stuck here, I don't have much background in `C#`.

**Comment by zacharyshupp** [comment]
I would like to switch over to using mRemoteNG at work but we have to have FIPS enabled. When we attempt to run the application we get that mRemoteNG isn't compatible with FIPS. Is this something that will be implemented in the future or is there a workaround to make it FIPS compliant?

**Comment by sparerd** [comment]
It looks like the library that we have used for crypto (BouncyCastle) has now gone through the compliance screening for FIPS. It looks like the encryption algorithms and modes that we are using are all valid when running in FIPS compliance mode, so we may be able to support FIPS with a bit of work.

There is an important distinction here, though. This change would mean mRemoteNG is using a crypto library which has been validated as FIPS compliant. However, mRemoteNG itself will not be FIPS _certified_. Using the crypto library in FIPS compliant mode might be enough to use mRemoteNG on systems with FIPS enforcement enabled but I'm not certain about that.

**Comment by sparerd** [comment]
BouncyCastle user guide for the FIPS compliant module:
https://downloads.bouncycastle.org/fips-csharp/BC-FNA-UserGuide-1.0.1.pdf

**Comment by veeramarni** [comment]
@sparerd Wondering if you have any input on when mRemoteNG will be FIPS compliant? As you said it was not a lot of work to make this change, so can we expect this to be working with FIPS pretty soon?

**Comment by cdmbasegtest** [comment]
What needs to done for make this tool FIPS compliant? I have some spare time to test it.

**Comment by rhardy613** [comment]
It is possible that this old tread from 2013 is currently still the problem?
i.e. the configuration encryption needed to be upgraded see: http://forum.mremoteng.org/viewtopic.php?f=3&t=1960
I too would love to see the need to disable FIPS fixed in mRemoteNG. I would classify that as a security bug. Suggesting a system level disable of FIPS is really bad from a security point of view.
While getting mRemoteNG certified might be useful for higher security environments I think the actual need here is much simpler. We need to do the minimum to allow mRemoteNG to install and operate on a FIPS compliant system. This simple use case does not require mRemoteNG itself to be certified. It simply needs to stop doing things that are incompatible with FIPS compliance.
On a system level, that in theory should be relatively simple to do but I'm not familiar with the code base. That may be as simple as having mRemoteNG default to encryption algorithms that are FIPS compliant. If it is necessary to support legacy systems where the current encryption algorithms support is missing fallback to the old methods either based on a config options or as an automatic fall back. Personally I wouldn't expect supporting legacy systems that don't support recent encryption algorithms needs to be a priority but that's up to the developers obviously.

**Comment by jsalian27** [comment]
Hi, Is there any fix to this issue with FIPS enabled on the Windows 2012R2 server?
Thanks.

**Comment by kmscode** [comment]
@sparerd 

Due to the changes you made in #157 - shouldn't we now be using FIPS acceptable algorithms? 

So long as the environments don't require full FIPS compliant/validated applications - we could hypothetically change the prompt here:
https://github.com/mRemoteNG/mRemoteNG/blob/v1.75Hotfix8/mRemoteV1/App/CompatibilityChecker.cs#L23

to add "proceed at your own risk" with OK or Exit buttons and get feedback from the community if this is acceptable. Seems like it should be based on the comments in this thread...

I could create a pre-release build at some point this week most likely.

Full disclosure: I haven't looked into this that much, so I don't know if I'm missing a big piece of the puzzle... 

Thoughts?

**Comment by kmscode** [comment]
@jsalian27 Not 100% sure if this will be "fixed" with my proposal. But it's a quick change that may work for a number of users - a good place to start with a minimal amount of code change. 

Hopefully will have a pre-release build available this week. I'll likely build off of the existing 1.76 (stable) branch, so it will be considered a "beta" release for now.

**Comment by jsalian27** [comment]
@kmscode That's great thanks Sean for your initiative to get a workaround on this and I will wait for your code release.Many Thanks.

**Comment by kmscode** [comment]
1.76.13 is an available pre-release for anyone that wants to test on FIPS enabled systems:
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.76.13

I tested on Windows 2016 with FIPS Enabled and connected successfully to another Windows 2016 system. Minimal, but it worked.

**Comment by jsalian27** [comment]
Thanks mate, I will get this tested in our dev environment and get back to you soon probably in Jan 2nd week.

**Comment by bcon** [comment]
So far the portable works great with no issues for what I use it for.

**Comment by Madj42** [comment]
Works here for me with FIPS enabled.  Thank you.

**Comment by jurlwin** [comment]
Works great here!

**Comment by kmscode** [comment]
All,

Thanks for your feedback on this.

I will get this code cleaned up and add a proper option so you're only prompted once (as opposed to on each startup). This will be released with 1.77 for sure... But if we have any plans for an official 1.76.* patch release (we don't at the moment), I'll be sure to get it included in there as well.

**Comment by jsalian27** [comment]
Thanks Sean works as expected and just 2 annoying pop-ups but as far as we can use it no issues.
Appreciate for quick turnaround on this.

**Comment by kmscode** [comment]
A better check was put in place and a new pre-release build is available:
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.76.14

This will be included in any future final versions of 1.76 (though none are planned at the moment) and will of course be included in 1.77.
