### ISSUE TITLE
Solution proposal to project problems

### ISSUE THREAD

**Issue by thetuxinator** [mRemoteNG/mRemoteNG#2317]
In my humble opinion this project is stuck and gets stuck more and more for the following reasons:

1. Tons of new feature requests every week
2. Nobody sorting those feature requests and not a single one seem to have been rejected (example https://github.com/mRemoteNG/mRemoteNG/issues/2296 where the author does not understand basics and thus sees a bug in it)
3. No feature freeze (deny new features till some are finished)
4. No minor maintenance releases with important fixes (like new puttyng) as all work is done on new features

Don't get me wrong, i see the efforts from the core developers, i just think the devs are swimming in tickets and have almost no time left to code, for that reason i would suggest to get a ticket moderation team which does some sort of first/second-level issues sorting and priorization.

Kind regards

**Comment by Kvarkas** [comment]
1. True, but that is positive wibe, it means for me that project is interesting and people are try to improve it, so all good
2. lol, just because you have different point of view its doesnt mean its wrong, and we have label for bugs, could you see such label under that request? So what you think and what I think its diametrical ;)
3. no point to freeze, and stop users imagination, but because I am only one who do coding these days - its a bit tricky, but I hope I have good track with versioning what and when will be implemented and I have plan (sorry its not visible) what to add so I keep suggestions to see if comunity like them or ignore - depending on that I decide what is priority to implement
4. puttyng released under different branch, perhaps I could acept that wasnt mentioned LAUDLY but if you not tracking such its not my fault 

And even if you show how unhappy you are I realy apriciated such, that means that project have place for improve and even critisizm is welcome (if its not to much anoing) I have a lot of plans to change it as well but curently is festive time and a lot of main activity on money making projects, this one is free (so far) but thinking to devide perhaps in version 2.x so we have free version still for home users but licenced for money for corporate users as they request a lot of new features what are useles for home users and will overload program interface. How ever that aproach may help to collect some funds to use them for frilancers hire so we can move project forward faster and quicker

**Comment by simonai1254** [comment]
Just to add my 50 cents:

1. (nothing to add)
2. I would say one can discuss about feature requests if they need to stay open (e.g., issues like #2296 mentioned by @thetuxinator do not imho) and how they added to the roadmap. For me a problem is that issues remain open even though they are solved because there are only a limited amount of people with the rights to close issues and the creator usually does not (e.g. #2282). This should be addressed (happy to help).
3. I get the point of feature freeze, though I'm not sure if that's the correct term. But one might state clearly with the roadmap that e.g. there will be exactly this features for version X and all other Features will be put back to version Y or even Z that's alright. The roadmap just needs to be clear.
4. I would support the minor support releases as well, especially as this is the only way to update all bundled software (e.g., log4net, PuttyNG). To focus specifically on PuttyNG: It might be maintained in a dedicated repository, but the end users just download the mRemoteNG installer which contains the verison that was out the date mRemoteNG was built.
I see two ways how to get around that: More frequent maintenance builds or requiring PuttyNG to be installed as dedicated utility like it's done with the .NET Desktop Runtime which is maintained externally. End users can not be expected to go and replace EXEs in the program files.

I'm not sure how I feel about commercializing this software, but I guess this discussion is somewhat for another time. In any case I appreciate your effort @Kvarkas :)

**Comment by Kvarkas** [comment]
roadmap yes good idea, will try to make it, in regards comercializing i just want to be clear - software as it is will stay free as much as I will be able to make it (about 20years at least for sure :D) but a lot features what are requested are for bussines users, and for home users where are will overload interface and not neede, so i am thinking only about add kind of plugins or extensions for this part only and only this part will cost something to companies, core will stay free

**Comment by Kvarkas** [comment]
closing as obsolete
