### ISSUE TITLE
%PASSWORD% & %USERNAME% for external tools only works with local username/password

### ISSUE THREAD

**Issue by DaveBurkhardt** [mRemoteNG/mRemoteNG#232]
%PASSWORD%/%USERNAME% does not populate with the global password/username (set in tools->options -> connections->"for empty username...")

I believe if local password config is empty %PASSWORD%, used for external tools, should be populated with the global password if it  is defined.  Current behavior just ignores the global setting.

Same applies to %USERNAME%

Not sure if this is a bug or feature request as I don't know what initial design was;  seems it's a bug to me.  If the connection itself is using the global credentials the external tools should be supplied the same credentials via %USERNAME% and %PASSWORD%.

thanks!

**Comment by kmscode** [comment]
https://mremoteng.atlassian.net/browse/MR-52

Description:
Related to Options field: "For empty Username, Password or Domain fields use:" it would be useful to be able to use just user and no global password.

This is specially useful when the configuration is shared between users (shared file or SQL) and each person has it's own user so they would use this global option to fill in they're user. But when using SSH keys or if using different passwords for each machine, mremoteng is sending the empty password to SSH server and windows closes (since authentication fails). 

-----
Comment:
Actually this is even simpler to fix: if the global password is empty do not send it as empty password!
The same as regular password works: if there's no password ask for one on connection.

Much simpler. 

-----

Appears to have been originally reported by @adrianandreias

**Comment by DaveBurkhardt** [comment]
> Comment:
>Actually this is even simpler to fix: if the global password is empty do not send it as empty password!
>The same as regular password works: if there's no password ask for one on connection.
>
>Much simpler.

I'm confused...

If the global is empty don't send it?  You don't need to code anything to achieve this.  The code currently does not look at the global credentials.  I don't feel you understand the scope of what it was I was asking for.

**Comment by farosch** [comment]
I don't know which version OP was using when reporting this issue but it seems to be resolved by now:

Settings:
![mRemoteNG_HswkVcZjFM](https://user-images.githubusercontent.com/22905106/66293949-227a2e00-e8e8-11e9-8bfd-79df6b2dfea1.png)

Connection:
![mRemoteNG_wt9ZMdJmLG](https://user-images.githubusercontent.com/22905106/66293952-25751e80-e8e8-11e9-8456-ab67def78f3c.png)

External Tool:
![mRemoteNG_6tEMq6pXr2](https://user-images.githubusercontent.com/22905106/66293955-273ee200-e8e8-11e9-8fb4-6bbf7f434b8a.png)

Output after running external tool:
![cmd_J9kseWg5Jp](https://user-images.githubusercontent.com/22905106/66293965-2a39d280-e8e8-11e9-838e-3442a43c9ee0.png)
