### ISSUE TITLE
SSH tunneling option is not shown

### ISSUE THREAD

**Issue by borekon** [mRemoteNG/mRemoteNG#2330]
When adding SSH connection, the option of SSH tunnel is not show

## Expected Behavior
The option should apper as seen in the following picture:
![imagen](https://user-images.githubusercontent.com/9289539/215039388-7e5d7f14-a774-432e-83de-9559008f85bd.png)

## Current Behavior
The option is not shown in portable version 1.76.20 (tried 1.77.1 as well)
![imagen](https://user-images.githubusercontent.com/9289539/215040707-e19df0c3-bdaa-4298-bc14-6ad943080672.png)

## Steps to Reproduce (for bugs)
1. Create new SSH connection

## Your Environment

* Version used: 1.76.20.24669
* Operating System and version (e.g. Windows 10 1709 x64): Windows 11 x64

**Comment by mister-alien** [comment]
Hi! I am able to reproduce this, but seems to be resolved as of the latest nightly build published in June 2022, I also confirmed that this issue is not present compiling the latest commit, so must have been a regression at some point.  

My suggestion would be to use a newer portable build, https://github.com/mRemoteNG/mRemoteNG/releases/tag/2022.06.13-v1.77.3-nb
![image](https://user-images.githubusercontent.com/6271728/215304948-3e724f26-fe80-4e7c-8df8-757553a66c7f.png)
