### ISSUE TITLE
I want to protect my account information by encrypting it

### ISSUE THREAD

**Issue by semirci** [mRemoteNG/mRemoteNG#235]
|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by semirci** [comment]
I want to protect my account information by encrypting it

**Comment by sparerd** [comment]
This feature already exists.

Custom encryption password can be set by clicking the root "Connections" node in the tree view and setting **Password protect** to `Yes`

You can turn on full file encryption (rather than just encrypting passwords) by going to Tools -> Options -> Advanced tab -> and check **Completely encrypt connection file**

**Comment by aplocher** [comment]
This is a feature I've used for many years with mRemoteNG but it's a bit buried.  It might be worth keeping this task (or adding a new one) to update the UI/UX and encourage users to utilize this.  In fact, maybe even make it mandatory in order to save passwords.  Just a thought...

**Comment by sparerd** [comment]
We are completely redoing the credential saving in the next next version (v1.76) which will fix this somewhat. Though I do agree with you that the UI/UX is pretty poor for some features (such as setting a custom encryption password). We have an outside group that may be taking a look at some of these UI blackholes in the future.

**Comment by sparerd** [comment]
Created #237 to look into improving the discover-ability of this feature
