### ISSUE TITLE
Issue "Ctrl + A" not working 

### ISSUE THREAD

**Issue by YoShiiro** [mRemoteNG/mRemoteNG#246]
Bug when modify the name of the "Connections"

When you open the name & modify, if you do CTRL + A, he not select all, he do nothing.

![image](https://cloud.githubusercontent.com/assets/6746150/20259776/01c70d5e-aa57-11e6-9ab9-935b48c9f7be.png)

|Operating system | Windows 10 x64 / Windows Server 2012 R2|
|mRemoteNG version| 1.74  |

**Comment by kmscode** [comment]
While I've validated that Ctrl +A doesn't work... Every test that I've run proves that this is a moot point:
* Right Click -> Rename
* Single Click (to select/highlight) -> F2 (to rename)
* Single Click (to select/highlight) -> Single Click (to rename)

All of these options have the same results: the name is completely selected by default. There is no need for Ctrl + A option is these scenarios. 

In scenario 3 (2 single clicks) - this doesn't work 100% properly if the item is already selected. Since the item is already selected, there is no need for the 2nd click. In this case the first click will edit with everything selected. The 2nd click will cause you to effectively de-select everything and place the cursor.

Closing this issue as the default functionality is superior.
