### ISSUE TITLE
How to disable clipboard sharing?

### ISSUE THREAD

**Issue by bar10dr** [mRemoteNG/mRemoteNG#2481]
## Expected Behavior
Go to settings for application, or settings per RDP connection and disable clipboard sharing.

## Current Behavior
No option to disable clipboard sharing.

## Possible Solution
Provide the ability to disable clipboard settings in the windows client.

## Steps to Reproduce (for bugs)
1. Select text
2. Press CTRL-C
3. Wait for an email from a collegue explaining that they are getting your data in their clipboard

## Context
I'm trying to prevent the items I put in my clipboard from being sent to other servers.

## Your Environment
* Version used: 1.76.20.24615
* Operating System and version (e.g. Windows 10 1709 x64): Windows 11

**Comment by rowich** [comment]
This is not a bug, it's a well working RDP feature - at least in all Windows versions I have ever worked with. If clipboard copying is enabled on the RDP guest, the clipboard-content is isolated in the specific session and only available/exchangeable with the connected client (here: mremoteng). There is no risk, that a colleague is able to view/get your clipboard accidentally.

**Comment by simonai1254** [comment]
Hi 

Generally there is a clipboard setting for each RDP connection, see here: https://github.com/mRemoteNG/mRemoteNG/issues/1562#issuecomment-528502502

Now I'm not sure what you mean with "your colleague means with getting your data" as the clipboard is bound to the user. It might work if you all use the same user on the servers (which you shouldn't), otherwise I don't see a problem here. Maybe you can explain your issue in this regard a little better? 

Regards

**Comment by Kvarkas** [comment]
its windows settings and we cant control that, we could allow or not allow share a clipboard from/to host and remote but on host is controled by windows. Potentialy we can add "flush" button what clean a clipboard before exit of app but not much we could do about it at the moment.
