### ISSUE TITLE
couldn't agree a host key algorithm ( available: rsa-sha2-512, rsa-sha2-256) when connecting to linux server

### ISSUE THREAD

**Issue by mukulmatta** [mRemoteNG/mRemoteNG#2520]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by mukulmatta** [comment]
using version 1.76.20.24615

but when i try to connect to same linux server using the putty, no issues. I assume MremoteNG using the default putty setting to make connection over ssh2

**Comment by simonai1254** [comment]
Hi

This is a known issue of versions below 1.77.2, see https://mremoteng.readthedocs.io/en/v1.77.3-dev/known_issues.html or https://github.com/mRemoteNG/mRemoteNG/issues/2027 for the solution.
Users are reporting that the custom Putty Path is not working correctly (see #2513), so just make sure to replace the PuttyNG.exe in the install directory according to the documentation.

The underlying issue is being tackled with https://github.com/mRemoteNG/mRemoteNG/issues/2454.

Have a good day
