### ISSUE TITLE
LocalSettingsManager class implementation is missing

### ISSUE THREAD

**Issue by frobenius** [mRemoteNG/mRemoteNG#2540]
I clone repository and i can't build mRemoteNg because class LocalSettingsManager declaration and implementation is not in repository.

**Comment by Kvarkas** [comment]
oh my bad, seems that bite leeked to repo then main part is not ready :) will fix, thanks for spoting.

**Comment by pahtzo** [comment]
Same issue here after cloning the repo.  Is there any timeline to resolve this? thank you.

**Comment by xRushG** [comment]
You don't need to wait for the fix if you've cloned the repo. Go to the file 'mRemoteNG\App\ProgramRoot.cs' and comment out (with // or /* [...] */) the lines as described in my comment for the merge: #2559. After you've done that, you can build the current version...

I'll try to start a second pull request in the next few days and comment out the lines. I don't want to delete them because I don't know if @Kvarkas needs them to complete the main part.

**Comment by pahtzo** [comment]
Thank you, that worked for me.

**Comment by HorseLuke** [comment]
Hello [xRushG](https://github.com/xRushG). mRemoteNG support portable mode. Did merge https://github.com/mRemoteNG/mRemoteNG/pull/2559 made portable mode not portable?

**Comment by xRushG** [comment]
Hey what exactly do you mean? Do you have an issue with compilation in visual studio?

**Comment by tecxx** [comment]
thanks for the programroot fix. 

i noticed as well that something changed with the portable version. is it intended that "release installer and portable" links to "release" configuration?

![image](https://github.com/mRemoteNG/mRemoteNG/assets/4305825/407f3dea-d67f-48f6-86f2-ee2d6fabaf1f)

**Comment by xRushG** [comment]
Ah, okay, I see. There have been some changes in the project configuration since March 31, 2023. Everything was changed to release, but therefore I can't tell anything. Please open a new ticket to report this feature.

![image](https://github.com/mRemoteNG/mRemoteNG/assets/145561288/6cf25e85-0cfc-4800-b1e6-8bfa2834b5e1)
