### ISSUE TITLE
Change in GeneralAppInfo.cs causes build failure

### ISSUE THREAD

**Issue by tecxx** [mRemoteNG/mRemoteNG#2592]
the recent commit https://github.com/mRemoteNG/mRemoteNG/commit/83f3846ce6349aea987874238c6d46f67b8164ea has a change in mRemoteNG/App/Info/GeneralAppInfo.cs

line 21 is now readonly
        public static readonly string ApplicationVersion = Application.ProductVersion;

this causes UpdaterTests.cs to fail building
![image](https://github.com/mRemoteNG/mRemoteNG/assets/4305825/893912c1-8836-40cb-9b27-1b9641fef943)

**Comment by xRushG** [comment]
I can confirm the error you encountered. It arises due to the limitations imposed by the nature of static classes and readonly fields. Since GeneralAppInfo is a static class with a readonly field ApplicationVersion, direct modification for testing purposes is not feasible within the current setup. However, one workaround is to introduce a protected static method within GeneralAppInfo that allows setting the application version internally, and then changing ApplicationVersion to have a private setter.

```csharp
public static string ApplicationVersion { get; private set; } = Application.ProductVersion;

public static void SetApplicationVersion(string version)
{
    ApplicationVersion = version;
}
```

You can then use SetApplicationVersion in NUnit tests. However, it's worth noting that this approach may not provide significant benefits, as there are no checks implemented in the setter method. I dont know.

I've encountered additional issues following the recent changes:
1)
![image](https://github.com/mRemoteNG/mRemoteNG/assets/145561288/9a5b73c5-a8ba-4f85-9e58-c1179fce8655)

To resolve this, I need to change the project settings' langVersion from 'latest' to 'preview'. However, I'm not sure if this is the best approach. What do you think?

2)
![image](https://github.com/mRemoteNG/mRemoteNG/assets/145561288/bebf8d98-a098-4626-a443-6203db809627)

Perhaps this is a typo:

```csharp
string detailsString = string.Join("; ", [.. details]);

```

The corrected version would be:

```csharp
string detailsString = string.Join("; ",  details);
```


Can anyone else confirm this?

Consider temporarily removing the read only flag for 'Application Version' in your local repository without committing the change. If you encounter the other two bugs, address them similar.

**Comment by xRushG** [comment]
Oh, forgot what i say....

Update Visual Studio to the latest version, and everything will be fine:

Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.10.0

Only the readonly flag needs to be removed:

```csharp
public static readonly string ApplicationVersion = Application.ProductVersion;
```

I'll take care of it.
