### ISSUE TITLE
Inquiry: mRemoteNG 1.76.20.24615 EOS Date

### ISSUE THREAD

**Issue by natixis-wz** [mRemoteNG/mRemoteNG#2639]
@Kvarkas
Hello! 
I am working to identify End of Life information for software in my client's environment to have a full picture of the asset’s lifecycle. As a part of this process, I am reaching out to inquire about the End of Support date for the following Software product/version:
•	mRemoteNG 1.76.20.24615
I was wondering if you could provide the End of Support and/or End of Life dates for the product listed above. If the dates are not yet announced, can you please confirm that detail? Additionally, it would be helpful if any documentation of these dates could be provided.
 
Thanks in advance!

**Comment by lars18th** [comment]
Hi @natixis-wz ,

After *years* waiting for an update, we can conclude that this software is dead. Although we do not want this, development is actually stalled. 😢

**Comment by Kvarkas** [comment]
> I was wondering if you could provide the End of Support and/or End of Life dates for the product listed above. If the dates are not yet announced, can you please confirm that detail? Additionally, it would be helpful if any documentation of these dates could be provided.
> 
> Thanks in advance!

where is no end of Life date planned. However product is keep developing and updates are merging into 1.77.3 version what have bunch of changes in code and covering security vulnerabilities and some improvements. I am planing keep working on it but bear in mind what I am only one developer and project is open source and could be use free of charge (we do accept donations but that not alot, like 70$ for a year) so I am spending my free time on it and its not much as many would like to see shiny new version :) However work never stop and I still planning to release soon stable build for testing, what have very strong potencial become a new release version later this year.

**Comment by AlexeyTorch** [comment]
> However product is keep developing and updates are merging into 1.77.3 version what have bunch of changes in code and covering security vulnerabilities and some improvements
Аre you kidding?
Changes merging to 1.77.3? A year and a half has passed since the launch of this Night Build.
I have to agree that the project is dead

**Comment by Kvarkas** [comment]
@AlexeyTorch are you dumb? 1.77.3 NB is alfa version updated regularly for testing purposes, it's not suppose to be used in live environment. But if you think what project is dead you are welcome to send money for a wreath: https://mremoteng.org/contribute

**Comment by wunderbar78** [comment]
You wanna know what's dumb? Fixing Security Vulnerablities and only release an alpha version for testing purposes only.
And there are only Alpha versions for 5 years. So yeah, of course people consider this project as dead.

And with such a response as above, I prefer to burn my money instead of donating it here.

I'm looking for an alternative now, even if I have to pay...

**Comment by kbjc11686** [comment]
I understand you are very busy and that this is not your primary source of income. I appreciate that this is open source software and I am sure that everybody above would like to see a new production release since they really do like this software. I think the concern is whether a contribution would mean that the release would for sure happen this year or not. I know you've mentioned previously that you expect a full release to come out multiple times now and it has not happened yet. So I think this is the cause for concern with asking for us to contribute when the code hasn't been updated in the production release as of yet. 

What I _**will say**_ is **if a major release comes out** I will guarantee a generous contribution for your efforts. I personally cannot justify contributing to this project until a new major release comes out. I appreciate all your efforts into this project and I would like to see your hard work pay off as well by others willing to contribute when a major release is available.

**Comment by Kvarkas** [comment]
Problem is not only I am busy, code is complicated and relay on libraries what have other issues, to change and fix one lead to malfunction another part, its like rabbit hole if you know what I mean, I keep trying to find a better solution or libs what dont have such issues as well as communicating with they authors to fix issues we relays on, we have couple of places with other devs who also struggling to fix (we keep trying) some parts we already manage to correct some others still looking how to do it, so I am not in hurry at all to release a version what everybody will blame and giggle on it, so release will be once all major issues will be fixed, and I a worked in user support, so I am resistant to impatients of users :) I do care what people love it and want it, but some who come only to cry like a baby who don't get a toy in shop and don't put any efforts for a project just blame it its die, what I could say, that problem of theys psychologist not our :)
In regards contributions, I take a lead of this project not for money (I have well paid primary job in cybersecurity btw my [linkedin](https://www.linkedin.com/in/gorodeckijdimitrij) in case you are interested) but because I love it and I apreachited support for ones who donate for a project, but idea to release stable version not getting money but to satisfy many users needs ;) so project is not dying, it's alive and progressing but many of you dont see whats happening on a background so be patient and hope soon you will see a new release ;)

**Comment by lars18th** [comment]
Hi @Kvarkas ,

- The problem is not that you are busy.
- The problem is not that there are a lot of problems to fix.
- The problem is not that too much time has passed since the last stable version.

The real problem is that no **nightly alpha builds** are provided with the **configuration enabled**.

We know what is an alpha build. And we want to contribute fixing/pointing the current issues. But without these binaries without configuration it is IMPOSSIBLE TO TEST.

Please reconsider your current position on this essential aspect.
And thank you for your effort! 👍

**Comment by Kvarkas** [comment]
you see, many people first run then read, we had this issue before, due a change in settings its mess-up with current version, and you don't know but I have statistic, and its over 3kk mR functioning in the world (at least ones we know was downloaded from our site) can you imaging what impact will be once user run it in production? :) thanks but no :) Once change will be ready (we move completely settings into local db) there will be no possible impact with older version then settings will be enabled
