### ISSUE TITLE
Feature request: RDP options

### ISSUE THREAD

**Issue by gerardsweeney** [mRemoteNG/mRemoteNG#272]
Is it possible to add an option to the RDP section so that we can add parameters such as enablecredsspsupport:i:0?

In our environment, we have RDP files with this option added as it speeds up the connection time.

Perhaps have a freeform text box, which - when populated - generates a temporary RDP file with the contents of the freeform text box added? (You might need some sanity checking like search replace existing values in generated RDP etc)

|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by sparerd** [comment]
I'm doubting that we would do this. It would likely be more work than simply adding the desired parameter to the program. Since we use the library version of RDP, it has no concept of how to load its parameters from an RDP config file (or any file really).

(Not sure if you were just using the CredSSP param as an example, but that option can already be set by enabling `Use CredSSP` on the connection record.)

**Comment by kmscode** [comment]
As @sparerd noted, CredSSP is already supported. We do support most RDP options allowed by the ActiveX client. 

If there are any specific options that are needed / desired that we don't currently support via the config section, feel free to open new issues accordingly...

However, allowing freeform would be asking for a lot of trouble since we'd have to validate all options passed in (from both a functionality and security point of view).

This request is not planned.
