### ISSUE TITLE
PowerShell Remoting Support

### ISSUE THREAD

**Issue by jrich523** [mRemoteNG/mRemoteNG#283]
It would be nice to have a powershell shell (powershell.exe would be fine) that we can use to remotely connect in to a system. 

Basically it would be like

powershell.exe -command "enter-pssession -computername $computername -credential (New-Object System.Management.Automation.PSCredential ($username, (ConvertTo-SecureString $password -AsPlainText -Force))

This could be used with the "external tool" provided there is a way to populate the computername/username/password from the connections details. Does it do anything spiffy for replacement or populating env vars?

**Comment by jrich523** [comment]
Thanks for the quick response, after RTFM'ing I think maybe i can make this work. testing now but i will say due to the complexity it might still be worth adding it in. PowerShell remoting is starting to get pretty popular.

**Comment by sparerd** [comment]
Just as a side note, there is a common-exttool entry for this. It's pretty much just what you wrote up in your initial post.

https://github.com/mRemoteNG/mRemoteNG/wiki/Common-External-Tool-Configurations#powershell-enter-pssession

I agree, native PS support would be a nice feature to add.

**Comment by ClairelyClaire** [comment]
Are there any plans to add this? I found a way to add it through ConEmu64 as a sort of process proxy, but that starts powershell inside cmd.exe, which prevents Ctrl+C script breaking from working.

**Comment by kmscode** [comment]
No immediate plans. We're focusing on some securing and maintaining the code at the moment. In some cases that means adding features (like the credential manager that is being worked on for 1.76), but otherwise some of the added features were "small". This might be a bit larger. 

Though I also agree, it would be great to have. If we can squeak it into 1.76 maybe, but I'd likely say 1.77 at this point.

**Comment by jrich523** [comment]
Nice!
