### ISSUE TITLE
RDP session disconnected

### ISSUE THREAD

**Issue by infectormp** [mRemoteNG/mRemoteNG#296]
- create 2 connection 
- set for 1 connection Panel=test
- set for 2 connection Panel=General
- open 1 connection (RDP)
- open 2 connection (SSH)

1 connection will be disconnected

|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75 beta 3  |

**Comment by sparerd** [comment]
I want to make sure I followed your replication instructions correctly:
1. create connection 1 (RDP) and set its panel=test
1. create connection 2 (SSH) and set its panel=General
1. Open connection 1
1. Open connection 2
1. We expect that connection 1 will be disconnected immediately when connection 2 connects

^^^ Following the above steps, I was not able to replicate the issue.

**Comment by infectormp** [comment]
@sparerd i try reproduce it tomorrow

**Comment by infectormp** [comment]
ok, i reproduce this

1. Set Russian language
2. create RDP connection, Panel=Главная
3. Switch laguage to English, restart app
4.create SSH connection, Panel=General
5. open 1 RDP connection then open SSH connection, exit from SSH

RDP connection will be disconnected

**Comment by sparerd** [comment]
Still not able to replicate. Would you be able to create a video of you replicating the issue? If you do, be sure to hide all sensitive information (host names/user names/etc). If necessary, I can provide a more secure method of sharing the information if you don't want to post it here.

**Comment by infectormp** [comment]
@sparerd enjoy
![session](https://cloud.githubusercontent.com/assets/9958813/20958090/d4b782d8-bc64-11e6-89e9-231819415856.gif)

**Comment by sparerd** [comment]
Ahhh, I see. This is due to the RDP session changing its draw area. When the client-side draw area changes, it informs the remote server what the new draw area is. Since this can only be set at connect-time, this triggers a reconnection.

I'm still not able to replicate, but @kmscode might have some more insight on what combo of settings may be causing this.

**Comment by infectormp** [comment]
But this not happens if both connection have same panel name.

If i move mRemoteNG to second screen, RDP disconnected due to the RDP session changing its draw area, but here it's look strange.

**Comment by sparerd** [comment]
Yep, several things are going on here. The setting for always showing panel tabs is not enabled, so when there is only 1 panel open, it will not show a tab. When this happens, you go from having 2 rows of tabs (panel tabs and connection tabs) to only having 1 row (connect tabs). This then causes the client area to get a bit bigger, triggering the RDP redraw and reconnection.

A way to test if this is the issue is to enable the following setting:
**Tools -> Options -> Tabs & Panels -> Always show panel tabs**

**Comment by kmscode** [comment]
@infectormp This is working as designed. This is due to the fact that when the 2nd panel is added or removed and only 1 panel remains, the RDP resolution changes. The default option of fit to panel causes the disconnect/reconnect.

The same thing would happen if you resize the mRemoteNG window (and thus the RDP session).

You can avoid this by forcing the RDP session to be a specific resolution (potentially a bit smaller than the overall window size when both panels are open), or:
Tools -> Options -> Tabs & Panels -> Check "Always show panel tabs".

This will force the general tab to always be displayed. Then opening a new panel, the RDP sessions resolution will not change, and will not disconnect/reconnect.

**Comment by kmscode** [comment]
@sparerd Damn. Beat me to it! by 39 seconds!

**Comment by sparerd** [comment]
;)

**Comment by infectormp** [comment]
:) 

my eyes can't see this resolution change, but you say this is working as designed so i close this issue. Maybe need describe this situation in FAQ.

**Comment by kmscode** [comment]
@infectormp You can reproduce the problem a few different ways as well...

Help -> About - this will open the "About" and "General" panels.... It's the height of the "General" panel, that adjusted the RDP resolution. It is quite small, but a change nonetheless. 

The same will happen with:
* Tools -> External Tools
* Tools -> SSH File Transfer
* Tools -> Port Scan

This might be something that we could possibly avoid in the future after replacing an old library that is in use for some of the tabs... This is already planned, but with no solid ETA: #155

**Comment by rustyjarz** [comment]
I was having this issue, but Tools -> Options -> Tabs & Panels -> Check "Always show panel tabs" has stopped this behavior for now. 

Thanks.
