### ISSUE TITLE
error 4360 when connecting to Windows 10 / Server 2012 r2 hosts

### ISSUE THREAD

**Issue by therealmrzippy** [mRemoteNG/mRemoteNG#328]
|||
|--:|---|
|Operating system | Windows 10 Pro x64 build 1607
|mRemoteNG version| 1.75.6179.28241

When attempting to connect to Windows 10 hosts  or Server 2012 r2 hosts, will often get error 4360. Tried disabling bitmap caching, connection timeout to 60, no luck. Advised to put in bug request per kmscode on reddit forum. Log attached. 

[mRemoteNGlog.txt](https://github.com/mRemoteNG/mRemoteNG/files/690350/mRemoteNGlog.txt)

**Comment by kmscode** [comment]
This one has me a bit stumped... 

Are you doing anything else at the time that the error has occurred?

Try setting "Automatic Resize" to "No" and let me know the results.

Thanks.

**Comment by therealmrzippy** [comment]
I did try that, no discernable difference. Weird thing is, it's intermittent. Sometimes it will work, sometimes it won't. Can be pretty frustrating :)

 

    On Tuesday, January 10, 2017 9:03 AM, Sean Kaim <notifications@github.com> wrote:
 

 This one has me a bit stumped...Are you doing anything else at the time that the error has occurred?Try setting "Automatic Resize" to "No" and let me know the results.Thanks.—

**Comment by tgrignon** [comment]
Have the same problem, I seen I need to close some concurrent session currently opened to be able to open a new one.

Like if mRemote have a memory or ressource limit et when it's reach cannot open other sessions.

**Comment by patrick-mackay** [comment]
I'm having the same problem here. Now it refuses to connect to almost every 2012+ server. The only machines that I can connect are 2008 R2.

My log is basically the same as therealmrzippy's.

2017-06-06 14:24:52,220 [1] INFO - Protocol Event Disconnected.
Message:
4360
Failed to reconnect to your remote session.
Please try to connect again.

All of them work with mstsc.exe. I logged out from the servers to check if the problem was with the opened sessions, but it doesn't connect.

Maybe is related, but debugging nremoteNg with windbg shows first chance exceptions in module nvwgf2um.dll, and is not the only error I'm getting with the latest nvidia driver. Paint.net stopped working after the driver update.

**Comment by patrick-mackay** [comment]
I downloaded the code and ran it in visual studio. When the error ocurrs, this is logged in the diagnostic tools window

Activated	Event	Time	Duration	Thread
	Exception: Exception thrown: 'System.InvalidOperationException' in System.Windows.Forms.dll ("Cross-thread operation not valid: Control 'olvConnections' accessed from a thread other than the thread it was created on."). Exception thrown: 'System.InvalidOperationException' in System.Windows.Forms.dll ("Cross-thread operation not valid: Control 'olvConnections' accessed from a thread other than the thread it was created on.")	84.60s		[26040] <No Name> 

But apparently it has nothing to do with the disconnection, since it ocurred after the close

![image](https://user-images.githubusercontent.com/4219141/26854423-17f544aa-4ae4-11e7-90d4-e527d712e7b6.png)

**Comment by patrick-mackay** [comment]
And finally, after installing the very latest nvidia driver (377.35-quadro-grid-desktop-notebook-win10-64bit-international-whql), nremoteNG is working as expected. All servers are connecting again, no first chance exceptions being logged in windbg console, and I didn't have to restart the application. 

The same instance of nRemoteNG that was not working an hour ago is working now.

**Comment by farosch** [comment]
#616

**Comment by farosch** [comment]
The current version of mRemoteNG has no problem opening 20+ RDP connections at once.
Since there is a high indication that this might have been a problem of the graphics card driver or the problem might have been fixed by the time the issue was made I will close this one.

**Comment by mabdulmoez** [comment]
I updated the drivers and made sure windows has installed all updates.

Then, I followed these steps: 

The next option is to disable UDP for RDP on client. This can be done through:
1.       GPO, navigate to computer configuration\Admin Templates\ Windows Components\Remote Desktop Services\Remote Desktop Connection Client -> Enable “Turn Off UDP On Client”
2.       Registry, HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\Client -> Set “fClientDisableUDP” to “1”

and the issue still persists.
