### ISSUE TITLE
Filter connections instead search.

### ISSUE THREAD

**Issue by areytsman** [mRemoteNG/mRemoteNG#338]
I have about 200 connections and when I make search on them I get a few results in a different places of list. Because the list does not fit entirely on the screen, I can not see all the results.
It would be great to filter the list displayed on the screen instead of searching.
Now I made my own fork of mRemoteNG and dirty hacked it to get filter, but I not have enough skills to make it clearly and make pull request.

P.S. I apologize in advance for any errors, I do not know English well enough.

**Comment by sparerd** [comment]
This should be very do-able with the new connection tree. It already has support for advanced filter searching. We just have to turn it on / configure it.

**Comment by kmscode** [comment]
@sparerd I think this would be a great feature for 1.76. Remove the milestone if you don't think it'll work for that timeline...

**Comment by sparerd** [comment]
Yea, this should be do-able for 1.76

**Comment by sparerd** [comment]
Implementation is done, though there is a caveat to the filtering at the moment. Filtering only considers items that are currently expanded. If a folder is collapsed, its children are not considered in filtering. Because of this, I'm going to leave this issue open and try to come back to it later when I have more time.

**Comment by sparerd** [comment]
On second thought, I'm going to close this issue and leave the filtering as-is. We will revisit if others find the above mentioned limitation a burden.
