### ISSUE TITLE
Please add checksums to the download to be able to verify file integrity.

### ISSUE THREAD

**Issue by michael-arion** [mRemoteNG/mRemoteNG#344]
Would it be possible to add some checksums in the release notes for each release?
That way the file integrity can be check upon downloading.

**Comment by kmscode** [comment]
The next release will have a checksum posted. This was already planned/implemented.

This is the new "update check file" that we are working on:
https://mremoteng.org/beta-update.txt

@benwa - anyway that we can easily publish the checksum on https://mremoteng.org/download ?

**Comment by benwa** [comment]
Not automatically with the [GitHub API](https://developer.github.com/v3/repos/releases/) unfortunately.  I could put a blurb about checking the changelog for checksums.

**Comment by kmscode** [comment]
Hmmm. Changelog.txt itself gets updated before the installer/zip is built since it is included in them. If we created some other file for gh-pages, would it be possible to read from it?

**Comment by benwa** [comment]
The current changelog link goes to pages like [this](https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75Beta2).

We could keep a database in the `_data` folder, but would need to keep track of all the versions by hand.

**Comment by sparerd** [comment]
*Might* be able to add a jenkins task for updating that. Pull the ghpages branch, append to _data, commit/push. Does it sound do-able?

**Comment by benwa** [comment]
I don't know much about Jenkins, but I believe that'll do it.  That db will hold all of the versions, so we can have that past releases table if you'd like.

**Comment by michael-arion** [comment]
I see the pages below, but no checksum for the current stable version.
The software intake process in the company I currently work for, has a requirement for verifiable downloads. Could you also add a stable.txt for example?

Thanks guys!

https://mremoteng.org/beta-update.txt
https://mremoteng.org/beta-update-portable.txt
https://mremoteng.org/dev-update.txt
https://mremoteng.org/dev-update-portable.txt
https://mremoteng.org/update.txt
https://mremoteng.org/update-portable.txt

**Comment by kmscode** [comment]
@michael-arion the checksums will be implmeneted in 1.75 beta 4 (or rc1, whatever we decide to call it) - which is the next release.

*update.txt and *update-portable.txt are the "stable" builds and will be updated once we get to releasing the 1.75 final.

We will work on getting the checksum listed on the download pages - we're just discussing how to make it less manual for us going forward... :wink:

**Comment by michael-arion** [comment]
@kmscode , could you confirm that the MD5sum for:
https://github.com/mRemoteNG/mRemoteNG/releases/download/v1.74/mRemoteNG-Installer-1.74.6023.15437.msi 
is this:
6292A53A8282B1B81250BD0372FF75D7 ?

I didn't find this MD5 in any of the *update*txt files mentioned above.
Thanks!

**Comment by rmcardle** [comment]
MD5 has been compromised for years and should no longer be used. If you are going to use hashes for this purpose, you need to use a cryptographically secure hash algorithm. MD5 most definitely is not.

Code signing using Authenticode is a much much better solution to this problem. Sign the individual executables and the installer package. Users can verify properly signed files right in Windows Explorer.

To be extra secure, publish the thumbprint of the signing certificate and instruct users how to verify it. You don't need to keep track of hashes for each file and each version you release, just the thumbprint for your signing certificate which will only change when your certificate expires.

**Comment by kmscode** [comment]
@rmcardle Thanks for the comments.

All released packages and binaries are Authenticode signed (unless otherwise noted in the release notes which was done a few times in the past for alpha releases - that practice has since been ceased). 

The specific request here is about verifiable downloads/file integrity since that is a company required. It is a simple matter to provide MD5 hashes. Looking into your comments further for file integrity the concerns are minimal as an attacker would need to specifically craft 2 files to get the same checksum. However, still a concern and noted. It's also a simple matter to provide a SHA512 hash going forward.

@michael-arion 
mRemoteNG-Installer-1.74.6023.15437.msi
MD5: 6292A53A8282B1B81250BD0372FF75D7
SHA512: AE6CC635684F5CC70DB445C248B55481D986E855358764E945A1D883615DB0194788B4AFA665F9583D3606089C98EBB3B32861A6FF39F5C7DAE058E3E7191D6B

Will provide SHA512 going forward.

**Comment by michael-arion** [comment]
Thanks a lot guys;
Of course a SHA512 is fine as well!

**Comment by rmcardle** [comment]
The whole point of code signing is to verify file integrity. It is significantly more secure than even the best hash algorithm because it also verifies the origin of the code. Anyone can hash a file, only one or two people in the world should be able to sign it with your certificate.

Consider the difference in difficulty between hacking your web server and changing the posted hash versus obtaining the private key for your certificate _and_ hacking your web server and changing the posted thumbprint of your certificate.

Using hashes to verify file integrity is cumbersome, error prone, and insecure and should not be encouraged. Especially since a better solution is already in place.

**Comment by sparerd** [comment]
I'm failing to see the issue here as we are already signing all released dll/exe/msi files using a publicly trusted cert. The hashes we provide are really just a secondary verification for those who want it. It's trivial to provide the hashes - it's already part of the release process.

**Comment by rmcardle** [comment]
Another point is that it would be significantly easier for a very determined attacker to compromise a user's copy of sha512sum.exe than it would be for them to compromise the Windows Authenticode system on a computer.

If users absolutely must verify the specific contents of a file (e.g. verify that this is version 1.1 not 1.0), you could use the Message Digest attribute in the Advanced tab of the Digital Signature Details dialog.

**Comment by rmcardle** [comment]
@sparerd Providing hashes, when there is a better, more secure system already in place, conditions users to rely on this outdated and insecure method of file verification. Users who don't understand Authenticode will just use the hash as their only authentication method and will be more vulnerable to attacks.

**Comment by sparerd** [comment]
Ok, I see your point now. We will take that into consideration for future releases.

**Comment by kmscode** [comment]
Hashes are included in the update.txt files accordingly. Hashes are otherwise unadvertised for now.
