### ISSUE TITLE
Can't connect to RDP sessions - Class not registered (0x80040154)

### ISSUE THREAD

**Issue by gilstrac** [mRemoteNG/mRemoteNG#404]
This looks similar and to have been addressed by issue https://mremoteng.atlassian.net/browse/MR-896
![image](https://cloud.githubusercontent.com/assets/1306987/22980451/b4e7d6c8-f356-11e6-9889-36837c92316e.png)
I verified KB2592687 has been applied.
thanks

 Windows 7 x64 
|mRemoteNG version 1.75 & 1.74

**Comment by sparerd** [comment]
It was also found that KB2574819 is required and that install order of KB2574819 and KB2592687 seems to matter.

See this article for more details:
https://github.com/mRemoteNG/mRemoteNG/wiki/FAQ#classnotreg

**Comment by nicoyn** [comment]
Hi guys,

I don't understand why there is such a regression :(
Im' using the portable version, because i'm working in a big company where I have very limited admin rights on my own station.  I don't even have access to installed KB...
RDP 6.1 is installed, I've successfully (re)registered the needed DLL, but i'm still stucked...

I'm so happy someone have resurrect this mRemoteNG project ! But I lose a functionnality here, RDP sessions is working like a charm on my old 1.70 version...

Any way to use the old way, instead of the non working new one ?

Cheers,

Nicolas.

**Comment by sparerd** [comment]
Unfortunately both KB2574819 and either KB2592687 or KB2923545 must be applied for the current RDP version to work. We could look into adding an option to downgrade the RDP version of a connection record, but this might take a bit of work to implement.

**Comment by gilstrac** [comment]
Following the above instructions fixed the issue.
