### ISSUE TITLE
Update 1.75.7005 to 1.75.7006 not possible - KB2574819 seem not be installed but it is

### ISSUE THREAD

**Issue by Marcusg562** [mRemoteNG/mRemoteNG#489]
|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.72.5065.32737  |

Update to actual Version not possible - Update package required but already installed. Update to actual Version and Version 1.74 not possible.

**Comment by kmscode** [comment]
Could you provide more details? I don't fully understand the problem that you are reporting.

The update from 1.72 to any later version must be done manually. The auto update functionality will not work due to new code signing keys.

**Comment by Marcusg562** [comment]
I've downloaded the actual version and tried to install it. But every time I get these error:
![image](https://cloud.githubusercontent.com/assets/105149/24859849/80bd7df0-1df2-11e7-89cb-96a51c8ad84f.png)

But this KB is already installed:
![image](https://cloud.githubusercontent.com/assets/105149/24859963/c71dbf94-1df2-11e7-9d18-68cd605cc03c.png)

The information in the Screenshot is german. Translations as follows:
Update for Windows (KB2574819) is already installed on this computer.

**Comment by azshane** [comment]
I am experiencing same problem. I have windows 7 x64 and the KB2574819 is already installed but the installation of Stable 1.75 hotfix 1 complains about it.  Please advise.

**Comment by Marcusg562** [comment]
Any updates here?

**Comment by azshane** [comment]
I had ver 1.74 which I the update failed on because of thinking KB2574819 was not installed but it was installed.  So I ended up saving my config to a file and do an export for safe side, then uninstalled 1.74 completed and installed 1.75 hotfix 1 fresh and it worked. then opened up my saved config file and save it in default directory appdata\roaming\mremoteng

**Comment by Marcusg562** [comment]
I've tried before a complete unsinatll and reinstall - also with deletion of Roaming Data - nothing happend same error again

**Comment by Marcusg562** [comment]
Addition information:
1.74 - release
1.75 - relase
1.75 - Hotfix 1-4 

Every version has the same issue - requires installed Windows KB but the zip works fine.

**Comment by kmscode** [comment]
@Marcusg562 @azshane 

Sorry for the delay...

Please see the following FAQ in regards to the Windows KB's:
https://github.com/mRemoteNG/mRemoteNG/wiki/FAQ#classnotreg

Even though that FAQ notes a different problem, we have seen some success with the prereq checks for the installation by performing the same procedure. However, you may just want to run the install and igore the prereq checks if you are 100% sure that all prereqs are installed:
https://github.com/mRemoteNG/mRemoteNG/wiki/Installing

We are still reviewing the installer via issue #466 

Please upvote follow that issue accordingly.

**Comment by Marcusg562** [comment]
REOPEN: Same issue with the new Update to v1.75.7006. This was not possible because of the same package. I will force install but I don't believe that this is the final solution.

**Comment by Marcusg562** [comment]
The only way to update for me was with this commandline installation:

`msiexec /i C:\Path\To\mRemoteNG-Installer.msi /qn IGNOREPREREQUISITES=1
`

**Comment by Marcusg562** [comment]
![2017-06-16 13_38_50-program manager](https://user-images.githubusercontent.com/105149/27225197-6acdbe5c-5299-11e7-93b1-adc6968075d1.png)

Issue during update 1.75.7006.16707 to 1.75.7008.17907

**Comment by donatelloOo** [comment]
You may need to manually download the KB fixes from Microsoft Knowledge Base here (be careful to choose the right version (x86 or x64) for your system) :

- https://support.microsoft.com/en-us/help/2830477 (RDP 8.1) : check all the dependency

or manually for RDP 8.0 (install them in that order) :
- https://support.microsoft.com/en-us/help/2574819 (DTLS support)
- https://support.microsoft.com/en-us/help/2592687 (RDP 8.0 update for Windows8 remote systems)

or manually for RDP 8.1 (install them in that order) :
- https://support.microsoft.com/en-us/help/2574819 (DTLS support)
- https://support.microsoft.com/en-us/help/2857650 (RDP update)
- https://support.microsoft.com/en-us/help/2830477 (RDP 8.1)
- https://support.microsoft.com/en-us/help/2913751 (RDP 8.1 / Smartcard issue)

That's said, mRemoteNG should not block and cancel the entire installation process, as those prerequisites could be impossible to install in an enterprise environment due to security policy.

Personally, I only use the SSH protocol, so issues on RDP protocol are the least of my worries (especially the Windows7 to Windows8 connectivity) !
Maybe we should be allowed to ignore those prerequisites using the installer (in graphical mode too), and be informed of the known issues.

**Comment by Marcusg562** [comment]
I've already updated with the commandline ;) The funny thing is as already described I've the KB fixes already installed only mRemoteNG doesn't recognize it. RDP and SSH works pretty good on my installation after forcing the update ;)

Cheers
Marcus

**Comment by sparerd** [comment]
Deferring this issue to v1.77. This will be resolved by #826 - we will no longer need to have requirements checked in the installer
