### ISSUE TITLE
mRemoteNG connection sync

### ISSUE THREAD

**Issue by JanRK** [mRemoteNG/mRemoteNG#522]
I've been using Remote Desktop Manager since the now fixed bug that wouldn't allow mRemoteNG to connect to more than 3-4 sessions on Win8. 

I really want to switch back, but I have become quite dependent on the cloud sync of my connection file. 

Is there any way to do this already? I remember before that it was pretty easy to get a corrupt confCons.xml file, when experimenting with this.

**Comment by kmscode** [comment]
The main/most common corruption issues should be fixed with #340 which is currently targeted for 1.76.

Also reference #409 where a user is requesting built in support for Cloud providers/multiple systems access. Many users will simply save the connection file to a cloud synced folder, but if you open the file on 2 different systems at the same time, you risk loss of changes or possible corruption. Concurrent connections as noted in #409 via the xml file is currently out of scope. At the moment, this would require the SQL feature which is still experimental and buggy. Feel free to upvote/follow the other issues accordingly.
