### ISSUE TITLE
Program Start after connection - Future Request

### ISSUE THREAD

**Issue by K1ng-Cr4zy** [mRemoteNG/mRemoteNG#539]
I'd like to start a program on the Remote Machine right after the connection. In mstsc i have the program tab like this:
![chat](https://cloud.githubusercontent.com/assets/28396842/25709570/fb3692e2-30e9-11e7-9855-16e4a0a8b3a6.png)

I think it could be useful.

Thank you and best regards.

**Comment by kmscode** [comment]
From Gitter conversation:
StartProgram : https://msdn.microsoft.com/en-us/library/aa382931(v=vs.85).aspx

This will run the specified program in place of the shell (Windows default shell being "exploer.exe").

Will need to research further if the referenced StartProgram property and the screen shot provide the same functionality.

**Comment by paraworlds2** [comment]
This would be an extremely helpful feature for our organization.

Here is an example of launching notepad when and rdp file is launched in Microsoft Remote Desktop Connection. These two lines were added to the RDP file when I created it using the Server 2003 Remote Desktop Connection. However, this has changed in later versions, since I don't see the Programs tab anymore in windows 10 and it doesn't work with my Server 2016, though this did work in windows server 2003 and will work with RemoteApps in 2012/2016. That being said, Remote Desktop Connection Manager v2.7 (RDMan) has this feature as well and it does work in those same two instances: 1. connecting to Windows Server 2003 and 2. connecting to Windows 2012/2016 that is set up with RDHS with the application you're trying to launch listed in the allowed applications (RemoteApp Programs). In RDMan, you go to the properties of a server and go to the "Connection Settings" tab and the settings are there for Start Program, Working dir, etc. Since we do have RDHS set up, this would work for us but it would need to be added to mRemoteNG as an option. Here are the two lines in the rdp that mRemoteNG would need to support.

**alternate shell:s:**c:\windows\system32\notepad.exe
**shell working directory:s:**c:\windows\system32

![start a program in rdman](https://user-images.githubusercontent.com/29807422/27757989-68e9611e-5dbf-11e7-9020-33aca5d73302.png)

**Comment by cdrum67** [comment]
This would be a very useful feature as remoteapp very useful and powerful and provides a good user experience when trying to lock down certain apps.

**Comment by sparerd** [comment]
I didn't realize that an earlier issue existed for this request until now. #327 is essentially the same request. In the interest of keeping our ticket queue in order, I'm going to close this issue as a duplicate. Please follow issue #327 for further updates.

Thank you to everyone for the good examples/conversation. This ticket will help when we do get around to implementing this.
