### ISSUE TITLE
What is the difference between a Hotfix and a Hotifx?

### ISSUE THREAD

**Issue by Eldaw** [mRemoteNG/mRemoteNG#597]
At first I thought it was a typo, but now I see that it's not just a one-off. The last few releases have all been labelled Hotifx.

**Comment by kmscode** [comment]
😖 

Due to the quite annoying bug with PuTTYNG, I was rushing to get out a solid release (7008 is solid). So I made a typo. I made that typo in a few spots (the readme which I think I caught before I published, the tag name which is less visable to users, the release title)... Then I copied and pasted the typo and modified the Hot**FI**x number without checking the little things like words and letters and stuff...

I'm not a fan of "hotfix" anyways... Maybe we'll call the next one "Patch 9" and maybe I won't screw up the release name again. Maybe.

Sorry for the confusion...
