### ISSUE TITLE
Double clic too quickly

### ISSUE THREAD

**Issue by joseaguardia** [mRemoteNG/mRemoteNG#614]
Hello.

In old versions I haven't this issue, but in this I enter in rename mode again and again in double clic instead of connect. Please, raise up the time of double clic.

Thanks!

Regards.

|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7000.19194  |

**Comment by kmscode** [comment]
Please test with the [latest release](https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75Hotfix8) and report back if you still have problems.

**Comment by kmscode** [comment]
In addition, the application doesn't control double click speed. This is a system setting. On Windows 10:
Settings -> Devices -> Mouse:
![image](https://user-images.githubusercontent.com/16654335/27654409-203fcab2-5c10-11e7-8ada-394645328429.png)

Additional Mouse Settings -> Buttons:
![image](https://user-images.githubusercontent.com/16654335/27654428-2b4016b0-5c10-11e7-8272-807ec49c37dc.png)

**Comment by jasonhpchu** [comment]
Alright, let me see if I can clarify this a bit more, since I do experience this minor annoyance.
Say you have two SSH connections on your connections list.
Double-click one to open up a session, then without clicking anywhere else, double-click a second connection to open up a session with the second connection.  The second double-click will not open up the session, but instead give you rename of the second connection setting's name.

**Comment by kmscode** [comment]
@jasonhpchu 

I cannot reproduce this at all...

I have a folder with 5 SSH connections in it. I can go down that list, doubling clicking on one after the other to connect with no other clicks in between and it only ever opens up the sessions in question.

To get to the rename, I have to single click a connection so that it's selected. Then single click the connection again.

I've tested this extensively. Sounds like you need to decrease your double click speed option, or double click faster.

**Comment by jasonhpchu** [comment]
That is strange.
I've tested with brand new mRemoteNG, and still got same results by setting up some dummy ssh connections.
So it must be some external environment related, and no, it's not my mouse/finger/doubleclick speed issue.  
I'm very certain I performed my consecutive double clicking maneuver correctly.... : )

Here's another hint.  I don't have the same issue if the connection is RDP or HTTP.  Only on the ones that bring out a black terminal screen would I have this issue.
