### ISSUE TITLE
Copy Paste stop working when mRemoteNG is working

### ISSUE THREAD

**Issue by Erez2017** [mRemoteNG/mRemoteNG#618]
|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by Erez2017** [comment]
Copy Paste stop working when mRemoteNG is working
Version: Stable v1.75.7008 (Hotifx 8)
Thu, Jun 15, 2017
Win 10

**Comment by kmscode** [comment]
Does copy and paste stop working in ALL apps or only between the local and remote systems?

**Comment by Erez2017** [comment]
Copy paste stop working only between local apps (on my laptop).
Copy paste between local apps to remote machines work properly.
On my laptop, once I copy, the paste in right click seems to be grayed out.
Once I close mRemoteNG, paste is active again and I can copy-paste

**Comment by kmscode** [comment]
That sounds extremely odd...

When paste is grayed out, if you were to Ctrl + V, would it still paste?

Are you generally in a remote session when this occurs? What type of session (RDP, SSH)? Or does this problem occur simply by opening mRemoteNG?

**Comment by Erez2017** [comment]
Yes, it is extremely odd indeed...
When paste is grayed out, Ctrl + V wouldn't pass either.
It happens only when mRemoteNG is opened and there are opened RDP sessions.
Bye the way, the problem was started when i updated mRemoteNG to latest
build. i didn't have any problem before this problem.



2017-06-28 21:33 GMT+03:00 Sean Kaim <notifications@github.com>:

**Comment by Erez2017** [comment]
before this update.

2017-07-02 18:03 GMT+03:00 Erez Cohen <erez4cohen@gmail.com>:

**Comment by johnjore** [comment]
I too had this issue, Windows 10 "upgraded" itself yesterday and cut/paste no longer worked when mRemoteNG was running with an active RDP session. Stop mRemoteNG or close all RDP sessions and cut/past worked again. 

Tested using Notepad on local machine, i.e. copy to/from same notepad instance on local machine.

I was on 1.23?!? something when problem started, upgraded to 1.75 Hotfix 8, still not working.

Also tried to disable "Redirect / Key Combi" in the RDP settings, no change.

Tried mstsc.exe on its own. Same issue, i.e. if using MSTSC.exe, cut/past stops working IF "Choose the devices and resource that you want to use in your remote session" "Clipboard" is ticket.

What's really strange is that after toggeling this off/on, problem is fixed in both MSTSC and mRemoteNG...

Oh joy...  YMMV

JJ

**Comment by sparerd** [comment]
Thanks for sharing your findings @johnjore!
