### ISSUE TITLE
An authentication error has occurred (Code: 0x800004005)

### ISSUE THREAD

**Issue by farlock85** [mRemoteNG/mRemoteNG#716]
I have a few RDP session that give the following error:
An authentication error has occurred (Code: 0x800004005).

The strange thing is when I connect to those servers through normal Windows RDP they work fine. I 10x checked if the credentials are correct and they are good.

I have 15 RDP sessions and it happens on 3 of them.

mRemoteNG: 1.75.7007
Windows 10 Pro 1703 15063.608

**Comment by farosch** [comment]
@farlock85 This is probably related to CredSSP or Windows remote authentication (kerberos/ntlm) settings on the machine you are trying to connect to. Since this is an old issue for an old version of mrng that has been inactive four quite a while now, I will close it. Please let us know, if this issue still persists for you and feel free to reopen this issue or create a new one if this is the case.
