### ISSUE TITLE
RDP connections are failing

### ISSUE THREAD

**Issue by santurmucik** [mRemoteNG/mRemoteNG#753]
RDP connections are failing to establish. Tried with FQDN, does not work.

|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008  |

**Comment by hctrr** [comment]
I'm experiencing the same thing. I can RDP using the native windows app, but for some reason mRemoteNG isn't able to RDP into it.
Note: This is occurring on multiple RDP attempts to different servers.

I'm also noticing that if established, connection might disconnect at times.

**Comment by a1d3s** [comment]
Same Problem after update to 7010 and tested with 7011 , rdp still not work
Windows 10 x64

**Comment by farosch** [comment]
@santurmucik @hctrr @a1d3s 
This is probably related to CredSSP settings on the server/in mrng or Windows remote authentication (kerberos/ntlm) settings on the machine you are trying to connect to.
Since this is an old issue for an old version of mrng that has been inactive four quite a while now, I will close it. Please let us know, if this issue still persists for you and feel free to reopen this issue or create a new one if this is the case!
