### ISSUE TITLE
Feature request: sorting in port scan results

### ISSUE THREAD

**Issue by kthordarson** [mRemoteNG/mRemoteNG#841]
It would be nice to be able to sort the port scan results by IP address, ports open etc. Also the option to switch from viewing hostnames to showing only IP address (or both).

**Comment by aniston** [comment]
any update on this Enhancement ?

It still does not seem to be possible to sort the port scan results by columns and still cannot see the IP instead of the hostname.

The IP is an important option for Importing connections as often the Hostname is not resolvable if using mRemoteNG thru VPN connections, also being able to scan only the given port range and import ALL open ports from that will be exotic :))
