### ISSUE TITLE
Enhancement - Push Inheritance from folder to all objects below

### ISSUE THREAD

**Issue by flyer292** [mRemoteNG/mRemoteNG#870]
Having the ability to enable inheritance on all object within a folder would save a lot of time for updating existing connections.

Same type of feature that is available on windows file security when you replace all child object permissions with inheritable permissions from this object

**Comment by sparerd** [comment]
Good idea. We will need to think about how this would work in the ui, but actual implementation shouldn't be too bad

**Comment by JRVcr** [comment]
I'd like to see inheritance enabled by default for new objects.

**Comment by malfuncion** [comment]
I was going to open this as a bug as it was working before updating to the latest beta. I have a set of connections nested below 1+ folders. So I have Top Level --> Client --> Service Account 1 and Service Acct 2 folders --> System Type  --> Groups of connections. The connection inherit from the system type folder, which then inherits from the SVC Account 1 and 2 folders above. In previous versions, this worked. With last update, no longer pushes down the tree. Noticed that I can set inheritance on the connection level and it works for that sessions only. Once I close the GUI and reload it is reverted on startup to "false" in the confCons.xml. Shutdown keeps the flags to "true". I also see an error about cannot load "donotplay" for object referring to sound passthrough. Possibly related, but not sure?

**Comment by penguinairlines** [comment]
I am also looking for this feature.  Changes in an environment, feature ads, and importing a co-worker's session file all warrant this as a value-able feature.  

For example, once I migrated between 2 versions of mRemoteNG and found that a new feature had been added "minutes to idle", which did not inherit on any of my existing credentials. In order to use this feature, I have to select each session/folder and change the inheritance for this feature to Yes.  Having the ability to recursively edit an inheritance property from a certain folder downwards would be extremely useful here.  I can also see an argument for applying the same with the Inherit All value, in a situation where a bunch of servers with individual credentials become attached to a domain.

**Comment by sparerd** [comment]
I have this one mostly implemented. It needs a bit more testing but should make it into v1.77

**Comment by JRVcr** [comment]
Good work, David; thanks! Happy to see development pace is picking up lately, too!

--

Jeff Vandervoort
Crescent IT Systems

**Comment by quokka-perth** [comment]
Hi Guys, I'm very much looking forward to propgating inheritance.... how close are we now?

**Comment by Kvarkas** [comment]
> Hi Guys, I'm very much looking forward to propgating inheritance.... how close are we now?

I also would like to implement/fix that so may say in upcoming version should be ok

**Comment by farosch** [comment]
This has been implemented by merging #1451
