### ISSUE TITLE
Add KiTTY support for PORTABLE mode

### ISSUE THREAD

**Issue by lars18th** [mRemoteNG/mRemoteNG#877]
Hi,

For PORTABLE mode will be more usefull to support the KiTTY INI configuration instead of the regular PuTTY configuration.

You agree?

**Comment by sparerd** [comment]
*Dev notes:*
To do this we will need to:
- [ ] Add a putty session provider to support loading kitty sessions from files
- [ ] Add stuff in the options page to allow defining the kitty path. We will need to decide whether kitty can be used side by side with putty or if it is an either-or choice.
--- If kitty and putty can be used together, we need to add a connectioninfo property to define which ssh provider to use. (We will need this anyway if we ever get around to supporting SSH.net #181)
-- If kitty will be used instead of putty, we need a way to detect that it is kitty so we can use the right session provider. Either determine this dynamically (give us a path, we will decide which provider to use), or explicitly (some toggle checkbox or drop down to declare which provider to use).
- [ ] Ensure that the connection tree node for putty connections displays "PuTTY Sessions" for normal putty and "KiTTY Sessions" for kitty to provide easy feedback to the user which provider is being used

**Comment by lars18th** [comment]
Hi @sparerd ,

Great to hear you aggree with my suggestion!
About the KiTTY and PuTTY use together:

1. You can use both at the same time, if you like. So _can_ be used together.
2. KiTTY has options (from commandline) for _import_ and _export_ to the PuTTY registry. You can consider to use it if you need it.
3. As KiTTY isn't the only PuTTY fork, I suggest to leave the user TWO config paths: one for the preferable SSH client using the registry and stock PuTTY entries; and another for the preferable _portable_ SSH client, in this case with the path for the config file/directory. So, when running mRemoteNG in PORTABLE mode you will use the _portable_ SSH client.

I hope you can include this suggestion in the roadmap.
Thank you!

**Comment by Miarka24** [comment]
This is essentially the same request I have: #851 
I am fine with Kitty too, same functionality better known.

Best Regards
Jonas Stunkat

**Comment by sparerd** [comment]
I'll close this request as duplicate in favor of #851 so we have everything in one place.
