### ISSUE TITLE
Not loading new translation files

### ISSUE THREAD

**Issue by onewithname** [mRemoteNG/mRemoteNG#878]
I am trying to translate to Lithuanian. Using the [wiki](https://github.com/mRemoteNG/mRemoteNG/wiki/Translate). However, even when I change something, save, compile and add .dll file to folder nothing changes.

This is what I get from regsen and al commands.
`c:\Projektai\mRemoteNG Lietuviskai>resgen /compile Language.lt.resx`
`Read in 66 resources from "Language.lt.resx"`
`Writing resource file...  Done.`

`c:\Projektai\mRemoteNG Lietuviskai>al /out:mRemoteNG.resources.dll /culture:lt /embedresource:Language.lt.resources`
`Microsoft (R) Assembly Linker version 14.0.1055.0`
`Copyright (C) Microsoft Corporation. All rights reserved.`

Then I move mRemoteNG.resources.dll file to ..\mRemoteNG\lt folder, and add `,lt` to SupportedUICultures tag in config file. Language shows in selection, but when I select it and restart, nothing changes.

Any ideas why?

**Comment by farosch** [comment]
@onewithname Sorry for the late reply!
If you are still interested in translating mRemoteNG I would very much like to provide the necessary support!

**Comment by onewithname** [comment]
Sure, I would like to help, when I have the time. However now when I am trying to load, language.resx. I am getting DTD security error.
`For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.`

**Comment by farosch** [comment]
Your previous attempt by following the article on the wiki failed, because this only works with languages that are already integrated into mrng.

I've done that just now with the above commit. You can test your translation with the portable build from here:
https://ci.appveyor.com/project/mremoteng/mremoteng/build/job/h6nn69kxgm2bbu61/artifacts

I've always struggled with Zeta, too... You can take a look at #1323 for a quick gif on how to edit the resx file.

**Comment by rupoase** [comment]
So, Zeta is a big pain in the back, opening translation files even from the GIF that @farosch provided, yields the same DTD error.
Since I've been working with resx files in the future, I know that they're just simply XML with XSD schema in them, so I've started from the english translation and duplicated it, renamed it into .ro.resx and started working on the translation.
Far easier and hassle free.
