### ISSUE TITLE
Cannot connect to RDP with different port

### ISSUE THREAD

**Issue by mathewarndt** [mRemoteNG/mRemoteNG#966]
In the new version, there is no RDP port specification.  I have a connection that uses port 3390.  I specified the port at the end of the IP address with the colon but the connection does not connect.

## Expected Behavior

I expect the connection to work with a different port.  It works with windows RDP connection.

## Possible Solution

Include the PORT as part of the address resolultion in connections.

## Steps to Reproduce (for bugs)

1. Put in the RDP address with a port number
2. No connection

## Context

Cannot connect to  RDP connections with a different port number.

## Your Environment

* Version used: 1.76.3.32991
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 1709 x64

**Comment by mathewarndt** [comment]
The issue is fixed.  For some reason, the port option did not appear when importing my connections.  But when I made a new connection, it returned.  And it works correctly.

**Comment by ptar** [comment]
The problem seems to be that the inheritance for the port is active for imported connections. Normally, this is quite useful, since the default RDP port is defined in the the first folder and inherited to all included connections.

So, instead of creating a new connection, just change the config of the existing connection:
- Switch to "Inheritance" (in Config-window)
- Double-click somewhere on the "Inherit Port" line : "Yes" will change to "No"
- Switch back to "Properties" (in Config-window)
- Cut out the imported port number from the field Hostname/IP (and remove the trailing ":")
- Paste the post number in the "Port" value by replacing the the default port number (3389)

Suggestion for a fix: During import, move the port-part of "Hostname/IP" to the port-field and disable port inheritance for this connection.

**Comment by BanditsAtZero** [comment]
Thank you, this was what I was looking for
