### ISSUE TITLE
Eventual application window resizing problem

### ISSUE THREAD

**Issue by parhamtk** [mRemoteNG/mRemoteNG#974]
## Expected Behavior
embed windows being in the current state of maximized or minimized## Current Behavior
 Some times when mouse curser Hover on the top side of the mremoteNG window, child windows or tabs changing from fullscreen to normal and unbind from general menu and no way to back into previous state
## Possible Solution
there is a work around but it needs to close mremoteNG and reopen all the connections
## Your Environment
Include as many relevant details about the environment you experienced the bug in
* Version used:
* Operating System and version: (Windows 8.1 1366 x768)

**Comment by farosch** [comment]
Closing for voidness: We don't even know what version OP is using.

> embed windows being in the current state of maximized or minimized

Don't know what this sentence should mean

> Some times when mouse curser Hover on the top side of the mremoteNG window, child windows or tabs changing from fullscreen to normal and unbind from general menu and no way to back into previous state

What times? At least try to narrow down the problem as much as possible.

> Include as many relevant details about the environment you experienced the bug in

You didn't include any...


Obviously closing this, since "some times this happens in a version i won't tell you about" is not a proper bug report...
