### ISSUE TITLE
Windows Update from RDP Connection about #kb4093120

### ISSUE THREAD

**Issue by cr1stt0f3r** [mRemoteNG/mRemoteNG#979]
Hello good afternoon.
Are you already aware of the new update of windows kb4093120?
This update is correcting a RDP connection vulnerability.

I make use of Windows 10 Pro Ver. 1803 Comp. 17134.48.

When trying to make connections to clients that do not have this update, the connection is not possible!

See for more details on:
https://support.microsoft.com/en-us/help/4093492/credssp-updates-for-cve-2018-0886-march-13-2018
https://support.microsoft.com/en-us/help/4093120/windows-10-update-kb4093120
https://portal.msrc.microsoft.com/en-us/security-guidance/advisory/CVE-2018-0886
https://support.microsoft.com/en-us/help/4056564/security-update-for-vulnerabilities-in-windows-server-2008

I imagine that with this information, you will be able to be careful and be aware of the improvements of the branch .

**Comment by kmscode** [comment]
kb4093120 "will enhance the error message that is presented when an updated client fails to connect to a server that has not been updated." The "problem" patch that addresses the CVE is [KB4103727 for 1709](https://support.microsoft.com/en-us/help/4103727/windows-10-update-kb4103727) or [KB4103721 for 1803](https://support.microsoft.com/en-us/help/4103721/windows-10-update-kb4103721) where the default has been changed to "Mitigated".

Due to the way mRemoteNG is designed and works (it uses the MS RDP libraries), this is 100% a patching/vendor issue. There is nothing for the project to do in relation to this. The onus is 100% within the environments being connected from/to.

Some other details can be found here:
https://github.com/mRemoteNG/mRemoteNG/issues/978#issuecomment-388376547

Options are to:

- Patch the servers accordingly
- Set the policy to vulnerable on the clients
- Uninstall KB4103727 or KB4103721 accordingly from the clients

See https://portal.msrc.microsoft.com/en-us/security-guidance/advisory/CVE-2018-0886 for additional details about the CVE and/or the patches for the other supported Windows versions.

Thanks!

**Comment by Dgreyvenstein** [comment]
I understand that it uses the underlying RDP libraries, but after patch KB4103727 has been installed, I can connect successfully with Windows RDP, but not with mRemoteNG. Is there a connection setting that I'm missing?

**Comment by kmscode** [comment]
@Dgreyvenstein the scenario where rdp works and mremoteng doesn't is very rare. I would recommend that you open a new issue, post the exact error and mremoteng.log so we can review this further.
