### ISSUE TITLE
Some controls clipped when Port Scan panel width is too small

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#990]
![image](https://user-images.githubusercontent.com/6999446/40888183-2947b2c2-6719-11e8-8c51-e693d5bec438.png)

## Expected Behavior
Controls should maintain distance from the right side and be moved left when the width is reduced.

## Current Behavior
Once window width gets to a certain point, some right-side controls stop being anchored to the right edge and just get clipped by the window.

## Your Environment

* Version used: v1.76.4
* Operating System and version: Windows 10 1709 x64

**Comment by farosch** [comment]
Redisigned that form, to at least reduce the possibility of elements being clipped off to a minimum. This is the smallest the form can be atm:
![image](https://user-images.githubusercontent.com/22905106/50384909-355ea180-06cc-11e9-856b-360cea63cafa.png)
Maybe increase the minimum size on the main form so that there is a definite minimum space available for other forms to be shown inside the main form?
